#!/bin/bash
# Per-project PostToolUse hook: Next.js type-check + lint
# Auto-generated by project-init

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

[[ -z "$FILE_PATH" ]] && exit 0

case "$FILE_PATH" in
  *.ts|*.tsx|*.js|*.jsx) ;;
  *) exit 0 ;;
esac

case "$FILE_PATH" in
  *node_modules*|*dist/*|*build/*|*.next/*) exit 0 ;;
esac

# Find project root (next.config.*)
DIR=$(dirname "$FILE_PATH")
PROJECT_ROOT=""
while [[ "$DIR" != "/" && "$DIR" != "." ]]; do
  if ls "$DIR"/next.config.* &>/dev/null || [[ -f "$DIR/package.json" ]]; then
    PROJECT_ROOT="$DIR"
    break
  fi
  DIR=$(dirname "$DIR")
done
[[ -z "$PROJECT_ROOT" ]] && exit 0

cd "$PROJECT_ROOT" || exit 0

ERRORS=""

# Type check
if [[ -f "tsconfig.json" ]]; then
  TYPE_OUTPUT=$(npx tsc --noEmit --pretty 2>&1)
  if [[ $? -ne 0 ]]; then
    ERRORS="TYPE CHECK ERRORS:\n$TYPE_OUTPUT"
  fi
fi

# Next.js lint
LINT_OUTPUT=$(npx next lint --no-cache 2>&1)
if [[ $? -ne 0 ]]; then
  ERRORS="$ERRORS\n\nLINT ERRORS:\n$LINT_OUTPUT"
fi

if [[ -n "$ERRORS" ]]; then
  TRUNCATED=$(echo -e "$ERRORS" | head -c 2000)
  echo "{\"systemMessage\": \"Validation errors after editing $FILE_PATH:\\n$TRUNCATED\"}"
fi

exit 0
