export type ProductCategory =
  | "all"
  | "ev-charging"
  | "solar-street"
  | "smart-home"
  | "cabinet"
  // | "container"
  ;

export type ProductVariation = {
  name: string;
  value: string;
  description?: string;
  price?: string; // Optional price for this variation
  image?: string; // Optional image for this variation
  specifications?: { label: string; value: string }[]; // Optional specifications for this variation
};

export type ProductLayout = "ev" | "b2b" | "auto"; // "auto" uses category-based default

export type Product = {
  id: string;
  name: string;
  subtitle: string;
  category: ProductCategory;
  tag?: string;
  image: string;
  images?: string[]; // Additional images for gallery
  price?: string; // Product price
  description?: string;
  variations?: ProductVariation[];
  specifications?: { label: string; value: string }[];
  features?: string[];
  layout?: ProductLayout; // Optional: specify which layout to use ("ev" or "b2b"), defaults to "auto" (category-based)
};

export const categories: { id: ProductCategory; label: string }[] = [
  { id: "all", label: "All Products" },
  { id: "ev-charging", label: "EV Charging Station" },
  { id: "solar-street", label: "Solar Street Lights" },
  { id: "smart-home", label: "Smart Home IPS" },
  { id: "cabinet", label: "Power Supplies" },
  // { id: "container", label: "Container Type Power Supply" },
];

export const categoryBanner: Record<
  ProductCategory,
  { title: string; description: string; image: string; video?: string }
> = {
  all: {
    title: "Energy Storage & Power Products",
    description:
      "From EV charging to smart home backup and utility-scale storage, VoltHub delivers trusted, safe and efficient power for every scenario.",
    image: "/resources/bulb.jpg",
  },
  "ev-charging": {
    title: "EV Charging Station Solutions",
    description:
      "Fast, reliable EV charging systems for homes, fleets and public sites, with smart monitoring and billing.",
    image: "/resources/charging-stats.jpg",
  },
  "solar-street": {
    title: "Solar Street Lighting Systems",
    description:
      "High‑efficiency solar street lights with intelligent control, built for streets, campuses and industrial parks.",
    image: "/aboutimages/solarstreetlight.jpg",
  },
  "smart-home": {
    title: "Smart Home IPS Backup",
    description:
      "Compact indoor power systems that keep your essential loads running during grid outages.",
    image: "/HomeBanner/homebatt.png",
    video: "/Product/SMVB.mp4",
  },
  cabinet: {
    title: "Power Supplies",
    description:
      "Modular cabinet energy storage and power supply systems for commercial and industrial applications.",
    image: "/resources/power-grid.jpg",
   // video: "/Product/CNvB.mp4",
  },
  // container: {
  //   title: "Container Type Power Supply",
  //   description:
  //     "Utility‑scale containerized BESS and hybrid power systems ready for rapid deployment.",
  //   image: "/HomeBanner/container.png",
  //   video: "/Product/CBMB.mp4",
  // },
};

// Based on Absen Energy products layout, adapted to VoltHub
// Reference: `https://www.absenenergy.com/en/product/`
export const products: Product[] = [
  // EV Charging Station products
  {
    id: "ev-dc-wd",
    name: "DC Wall Charger Single Gun",
    subtitle: "Compact wall-mounted DC fast charger for residential and commercial parking",
    category: "ev-charging",
    tag: "Wall-Mounted DC Charger",
    image: "/Product/EV/new/ta-dc-wd.png",
    images: ["/Product/EV/new/ta-dc-wd.png", "/Product/EV/new/ta-dc-wd-lifestyle1.png", "/Product/EV/new/ta-dc-wd-lifestyle2.png"],
    description: "TA-DC-WD — 7kW to 40kW single-gun wall-mounted DC fast charger. Supports CCS1, CCS2, GB/T, and CHAdeMO connectors. Features 5-inch color touch screen, RFID card, APP, and OCPP connectivity. IP54 rated for indoor/outdoor use.",
    layout: "ev",
  },
  {
    id: "ev-dc-wdd",
    name: "DC Wall Charger Dual Gun",
    subtitle: "High-power wall-mounted DC charger with dual charging guns",
    category: "ev-charging",
    tag: "Wall-Mounted DC Charger",
    image: "/Product/EV/new/ta-dc-wdd.png",
    images: ["/Product/EV/new/ta-dc-wdd.png", "/Product/EV/new/ta-dc-wdd-lifestyle1.png", "/Product/EV/new/ta-dc-wdd-lifestyle2.png"],
    description: "TA-DC-WD(D) — 40kW to 80kW dual-gun wall-mounted DC fast charger. Supports simultaneous charging of two vehicles. Features 7-inch color touch screen, swipe card, APP, and OCPP management. IP54 rated.",
    layout: "ev",
  },
  {
    id: "ev-dc-wdm",
    name: "DC Wall Charger Curved Design",
    subtitle: "Sleek curved-body wall-mounted DC charger for modern installations",
    category: "ev-charging",
    tag: "Wall-Mounted DC Charger",
    image: "/Product/EV/new/ta-dc-wdm.png",
    images: ["/Product/EV/new/ta-dc-wdm.png", "/Product/EV/new/ta-dc-wdm-lifestyle1.png", "/Product/EV/new/ta-dc-wdm-lifestyle2.png"],
    description: "TA-DC-WDM — 7kW to 40kW single-gun curved-body wall-mounted DC charger. Premium design with smooth contours. Supports CCS1, CCS2, GB/T, and CHAdeMO. IP54 rated.",
    layout: "ev",
  },
  {
    id: "ev-dc-dd",
    name: "DC Floor Charger Dual Gun",
    subtitle: "Robust floor-standing dual-gun DC fast charger for public and commercial sites",
    category: "ev-charging",
    tag: "Floor-Standing DC Charger",
    image: "/Product/EV/new/ta-dc-dd.png",
    images: ["/Product/EV/new/ta-dc-dd.png", "/Product/EV/new/ta-dc-dd-lifestyle1.png", "/Product/EV/new/ta-dc-dd-lifestyle2.png"],
    description: "TA-DC-DD — 40kW to 80kW dual-gun floor-standing DC fast charger. Features 7-inch touch display, RFID card, APP, OCPP, and load balancing. IP54 rated. Ideal for public charging stations and fleet operations.",
    layout: "ev",
  },
  {
    id: "ev-dc-fd",
    name: "DC Cabinet Charger",
    subtitle: "High-power cabinet-type floor-standing DC fast charger",
    category: "ev-charging",
    tag: "Floor-Standing DC Charger",
    image: "/Product/EV/new/ta-dc-fd.png",
    images: ["/Product/EV/new/ta-dc-fd.png", "/Product/EV/new/ta-dc-fd-lifestyle1.png", "/Product/EV/new/ta-dc-fd-lifestyle2.png", "/Product/EV/new/ta-dc-fd-lifestyle3.png"],
    description: "TA-DC-FD — 60kW to 120kW cabinet-type floor-standing DC fast charger with one or two guns. Features 7-inch color touch screen, quick/slow charge automatic switch. IP54 rated. Built for high-traffic public charging stations.",
    layout: "ev",
  },
  {
    id: "ev-dc-fq-60",
    name: "DC Floor Charger FQ 60-80kW",
    subtitle: "Medium-power floor-standing dual-gun DC charger for public stations",
    category: "ev-charging",
    tag: "Floor-Standing DC Charger",
    image: "/Product/EV/new/ta-dc-fq-60.png",
    images: ["/Product/EV/new/ta-dc-fq-60.png", "/Product/EV/new/ta-dc-fq-60-lifestyle1.png", "/Product/EV/new/ta-dc-fq-60-lifestyle2.png"],
    description: "TA-DC-FQ — 60kW to 80kW floor-standing dual-gun DC fast charger. Supports CCS1, CCS2, GB/T, and CHAdeMO. Ideal for medium-traffic public charging stations and commercial parking.",
    layout: "ev",
  },
  {
    id: "ev-dc-fq-120",
    name: "DC Floor Charger FQ 120-180kW",
    subtitle: "High-power floor-standing dual-gun DC fast charger for heavy-duty sites",
    category: "ev-charging",
    tag: "Floor-Standing DC Charger",
    image: "/Product/EV/new/ta-dc-fq-120.png",
    images: ["/Product/EV/new/ta-dc-fq-120.png"],
    description: "TA-DC-FQ — 120kW to 180kW floor-standing dual-gun DC fast charger. Supports CCS1, CCS2, GB/T, and CHAdeMO. Designed for high-traffic public charging hubs and highway rest areas.",
    layout: "ev",
  },
  // Solar Street Lights products
//   {
//     id: "solar-street-f1l",
//     name: "F1L Solar Street Light",
//     subtitle: "High-efficiency solar street lighting system",
//     category: "solar-street",
//     tag: "Integrated Light",
//     image: "/Product/StreetLamp/F1L.png",
//   },
  {
    id: "solar-street-f2l",
    name: "Integrated Lamp F2 Series",
    subtitle: "The Light of Energy, Crefted with Ingenuity",
    category: "solar-street",
    tag: "Integrated Light",
    image: "/Product/StreetLamp/F2L.png",
    images: [
      "/Product/StreetLamp/F2L.png",
      "/Product/StreetLamp/f2/prod4.png",
      "/Product/StreetLamp/f2/disc1.png",
      "/Product/StreetLamp/f2/disc2.png",
      "/Product/StreetLamp/f2/disc3.png",
      "/Product/StreetLamp/f2/disc4.png",
      "/Product/StreetLamp/f2/disc5.png",
      "/Product/StreetLamp/f2/disc6.png",
    ],
  },
  {
    id: "solar-street-rklv02",
    name: "Road King-LV02",
    subtitle: "Compact solar street lighting system",
    category: "solar-street",
    tag: "Split Street Light",
    image: "/Product/StreetLamp/RKlv02.png",
    images: [
      "/Product/StreetLamp/RKlv02.png",
      "/Product/StreetLamp/lvxc2/prod1.png",
      "/Product/StreetLamp/lvq2/disc1.png",
      "/Product/StreetLamp/lvq2/disc2.png",
      "/Product/StreetLamp/lvq2/disc3.png",
      "/Product/StreetLamp/lvq2/disc4.png",
      "/Product/StreetLamp/lvq2/disc5.png",
      "/Product/StreetLamp/lvq2/disc6.png",
      "/Product/StreetLamp/lvq2/disc7.png",
    ],
  },
  {
    id: "solar-street-rks",
    name: "Solar Road King Series LVXC2",
    subtitle: "Premium solar street lighting solution",
    category: "solar-street",
    tag: "All in Two Light",
    image: "/Product/StreetLamp/RKS.png",
    images: [
      "/Product/StreetLamp/RKS.png",
      "/Product/StreetLamp/lvq2/prod1.png",
     // "/Product/StreetLamp/lvxc2/disc1.png",
      "/Product/StreetLamp/lvxc2/disc2.png",
      "/Product/StreetLamp/lvxc2/disc3.png",
      "/Product/StreetLamp/lvxc2/disc4.png",
      "/Product/StreetLamp/lvxc2/disc5.png",
      "/Product/StreetLamp/lvxc2/disc6.png",
      "/Product/StreetLamp/lvxc2/disc7.png",
      "/Product/StreetLamp/lvxc2/disc8.png",
    ],
  },
  {
    id: "solar-street-lvxc",
    name: "Solar Road King Series LVXC3",
    subtitle: "High-performance solar street lighting system",
    category: "solar-street",
    tag: "All in Two Light",
    image: "/Product/StreetLamp/LVXC.png",
    images: [
      "/Product/StreetLamp/LVXC.png",
      "/Product/StreetLamp/lvxc3/prod1.png",
   // "/Product/StreetLamp/lvxc3/disc1.png",
      "/Product/StreetLamp/lvxc3/disc2.png",
      "/Product/StreetLamp/lvxc3/disc3.png",
      "/Product/StreetLamp/lvxc3/disc4.png",
      "/Product/StreetLamp/lvxc3/disc5.png",
      "/Product/StreetLamp/lvxc3/disc6.png",
      "/Product/StreetLamp/lvxc3/disc7.png",
      "/Product/StreetLamp/lvxc3/disc8.png",
    ],
  },
  // Smart Home IPS products
  {
    id: "smart-home-smp2",
    name: "Smart Home IPS 5kWh",
    subtitle: "Residential Smart Home Power System",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP2.png",
    images: [
      "/Product/SmartHome/SMP2.png",
      "/Product/SmartHome/2B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp3",
    name: "Smart Home IPS 10kWh",
    subtitle: "Standard Home / Small Business Power System",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP3.png",
    images: [
      "/Product/SmartHome/SMP3.png",
  
      "/Product/SmartHome/3B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp4",
    name: "Smart Home IPS 15kWh",
    subtitle: "Longer Backup, Same Power",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP4.png",
    images: [
      "/Product/SmartHome/SMP4.png",
      "/Product/SmartHome/4B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp5",
    name: "Smart Home IPS 20kWh",
    subtitle: "Larger Home / Small Commercial",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP5.png",
    images: [
      "/Product/SmartHome/SMP5.png",
    
      "/Product/SmartHome/5B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp6",
    name: "Smart Home IPS 25kWh",
    subtitle: "More Hours, Same Power",
    category: "smart-home",
    layout: "ev", // Use EV layout for this product
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP6.png",
    images: [
      "/Product/SmartHome/SMP6.png",
      "/Product/SmartHome/6B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp7",
    name: "Smart Home IPS 30kWh",
    subtitle: "Mini-Microgrid",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP7.png",
    images: [
      "/Product/SmartHome/SMP7.png",
      "/Product/SmartHome/7B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  // Cabinet Type Power Supply products
  {
    id: "cabinet-14",
    name: "Cabinet Type Power Supply 215kWh",
    subtitle: "Village / Industrial-Scale Microgrid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/200kwh.png",
    images: [
      "/Product/cabinet/200kwh.png",
      "/Product/cabinet/cb14/prod2.png",
      "/Product/cabinet/cb14/prod3.png",
      "/Product/cabinet/cb14/prod4.png",
    ],
  },
  {
    id: "cabinet-15",
    name: "Cabinet Type Power Supply 522kWh",
    subtitle: "Large-Scale Industrial / Community Microgrid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/500kwh.png",
    images: [
      "/Product/cabinet/500kwh.png",
      "/Product/cabinet/cb15/prod1.png",
      "/Product/cabinet/cb15/prod2.png",
      "/Product/cabinet/cb14/prod2.png",
    ],
  },
  {
    id: "cabinet-16",
    name: "Cabinet Type Power Supply 783kWh",
    subtitle: "Village or Island Grid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/700kwh.png",
    images: [
      "/Product/cabinet/700kwh.png",
      "/Product/cabinet/cb16/prod1.png",
      "/Product/cabinet/cb16/prod2.png",
      "/Product/cabinet/cb16/prod3.png",
      "/Product/cabinet/cb14/prod2.png",
    ],
  },
  {
    id: "cabinet-item4",
    name: "Cabinet Type Power Supply 40kWh",
    subtitle: "Small Commercial / Remote Facility",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/20.png",
    images: [
      "/Product/cabinet/20.png",
      "/Product/cabinet/30.png",
      "/Product/cabinet/40.png",
      "/Product/cabinet/50.png",
      "/Product/cabinet/disc1.png",
      "/Product/cabinet/disc2.png",
      "/Product/cabinet/disc3.png",
    ],
  },
  // Container Type Power Supply products
  {
    id: "container-con1",
    name: "Container Type Power Supply",
    subtitle: "Utility-scale containerized BESS and hybrid power system",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/containertype/con1.png",
    images: [
      "/Product/containertype/con1.png",
      "/Product/containertype/prod1.png",
      "/Product/containertype/prod2.png",
      "/Product/containertype/prod3.png",
      "/Product/containertype/prod4.png",
      "/Product/containertype/prod5.png",
      "/Product/containertype/prod6.png",
    ],
  },
];

// Helper function to get product by ID
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

// Extended product details (can be expanded with more details)
export const productDetails: Record<string, {
  description: string;
  variations: ProductVariation[];
  specifications: { label: string; value: string }[];
  features: string[];
}> = {
  "ev-dc-wd": {
    description: "TA-DC-WD — 7kW to 40kW single-gun wall-mounted DC fast charger. Supports CCS1, CCS2, GB/T, and CHAdeMO connectors. Features 5-inch color touch screen, RFID card, APP, and OCPP connectivity. IP54 rated for indoor/outdoor use. Ideal for residential garages, apartment parking, and small commercial sites. Plug-and-charge with optional load balancing for smart grid integration.",
    variations: [
      { name: "7kW Model", value: "TA-DC-WD 7kW", description: "Output: 7kW | Voltage: 50-750V | Current: 0-20A | Input: 100-280V, L+N+PE | Size: 450×340×165mm" },
      { name: "15kW Model", value: "TA-DC-WD 15kW", description: "Output: 15kW | Voltage: 200-1000V | Current: 0-60A | Input: 280-500V, 3P+N+PE | Size: 660×470×248mm" },
      { name: "20kW Model", value: "TA-DC-WD 20kW", description: "Output: 20kW | Voltage: 200-1000V | Current: 0-60A | Input: 280-500V, 3P+N+PE | Size: 660×470×248mm | Weight: 64.5kg" },
      { name: "30kW Model", value: "TA-DC-WD 30kW", description: "Output: 30kW | Voltage: 200-1000V | Current: 0-100A | Input: 280-500V, 3P+N+PE | Size: 660×540×280mm | Weight: 73kg" },
      { name: "40kW Model", value: "TA-DC-WD 40kW", description: "Output: 40kW | Voltage: 200-1000V | Current: 0-133A | Input: 280-500V, 3P+N+PE | Size: 660×540×280mm | Weight: 87.75kg" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-WD" },
      { label: "Output Power", value: "7kW / 15kW / 20kW / 30kW / 40kW" },
      { label: "Output Voltage", value: "50-750V (7kW) / 200-1000V (15-40kW)" },
      { label: "Input Voltage", value: "100-280V (7kW) / 280-500V (15-40kW)" },
      { label: "Output Current", value: "0-20A (7kW) / 0-60A (15-20kW) / 0-100A (30kW) / 0-133A (40kW)" },
      { label: "Input Connection", value: "L+N+PE (7kW) / 3P+N+PE (15-40kW)" },
      { label: "Display", value: "5-inch color touch screen" },
      { label: "IP Rating", value: "IP54" },
      { label: "Gun Cable Length", value: "5M (customizable)" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Interface Standard", value: "CCS1, CCS2, GB/T, CHAdeMO" },
      { label: "Charging Mode", value: "Plug & charge, RFID card, APP, OCPP" },
      { label: "Installation", value: "Wall-mounted" },
    ],
    features: [
      "Compact wall-mounted design saves floor space",
      "5-inch color touch screen for intuitive operation",
      "Supports CCS1, CCS2, GB/T, and CHAdeMO connectors",
      "Plug-and-charge with RFID card and APP control",
      "OCPP 1.6 compliant for remote management",
      "Optional load balancing for smart grid integration",
      "IP54 rated for indoor and outdoor installation",
      "Wide power range from 7kW to 40kW",
      "Charging protocol: GBT27930, CHADEMO 2.0, ISO 15118",
      "5M gun cable length (customizable)",
    ],
  },
  "ev-dc-wdd": {
    description: "TA-DC-WD(D) — 40kW to 80kW dual-gun wall-mounted DC fast charger. Supports simultaneous charging of two vehicles via CCS1, CCS2, GB/T, or CHAdeMO. Features 7-inch color touch screen, swipe card, APP, and OCPP management. IP54 rated. Ideal for commercial parking garages, fleet depots, and multi-unit residential complexes requiring higher throughput.",
    variations: [
      { name: "40kW Model", value: "TA-DC-WDD 40kW", description: "Output: 40kW | Voltage: 150-1000V | Current: 0-125A | Input: 285-475V, 63A | Dimensions: 90×78.9×27.5cm | Weight: 120kg" },
      { name: "60kW Model", value: "TA-DC-WDD 60kW", description: "Output: 60kW | Voltage: 150-1000V | Current: 0-200A | Input: 260-530V, 105A | Dimensions: 90×78.9×27.5cm | Weight: 130kg" },
      { name: "80kW Model", value: "TA-DC-WD(D) 80kW", description: "Output: 80kW | Voltage: 150-1000V | Current: 0-200A | Input: 260-530V, 130A | Size: 1025×725×625mm | Weight: 159kg" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-WD(D)" },
      { label: "Output Power", value: "40kW / 60kW / 80kW" },
      { label: "Output Voltage", value: "150-1000V" },
      { label: "Input Voltage", value: "285-475V (40kW) / 260-530V (60-80kW)" },
      { label: "Output Current", value: "0-125A (40kW) / 0-200A (60-80kW)" },
      { label: "Gun Quantity", value: "Two (CCS-1/CCS-2/CHAdeMO/GBT)" },
      { label: "Gun Rated Current", value: "125A (40kW) / 200A (60kW)" },
      { label: "Display", value: "7-inch color touch screen" },
      { label: "IP Rating", value: "IP54" },
      { label: "Frequency", value: "50/60 Hz" },
      { label: "Operating Temperature", value: "-20°C to +75°C (reduce frequency above 55°C)" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Charging Mode", value: "Swipe card / APP / Network" },
      { label: "Network", value: "CAN/485 / Ethernet / GPRS/4G" },
    ],
    features: [
      "Dual-gun simultaneous charging for two vehicles",
      "7-inch color touch screen interface",
      "Supports CCS1, CCS2, CHAdeMO, and GB/T connectors",
      "Swipe card, APP, and network charging modes",
      "OCPP 1.6 compliant with load balancing support",
      "IP54 rated for reliable outdoor operation",
      "Wall-mounted design maximizes parking space",
      "40kW to 80kW power range for flexible deployment",
      "CAN/485, Ethernet, and GPRS/4G connectivity",
      "Operating temperature range: -20°C to +75°C",
    ],
  },
  "ev-dc-wdm": {
    description: "TA-DC-WDM — 7kW to 40kW single-gun curved-body wall-mounted DC charger. Premium design with smooth contours for modern installations. Supports CCS1, CCS2, GB/T, and CHAdeMO. Features 5-inch display, RFID card, APP, OCPP, and optional load balancing. IP54 rated. Same powerful internals as the WD series in a sleek, contemporary form factor.",
    variations: [
      { name: "7kW Model", value: "TA-DC-WDM 7kW", description: "Output: 7kW | Voltage: 50-750V | Current: 0-20A | Input: 100-280V, L+N+PE | Size: 450×310×150mm | Weight: 37.1kg" },
      { name: "15kW Model", value: "TA-DC-WDM 15kW", description: "Output: 15kW | Voltage: 200-1000V | Current: 0-60A | Input: 280-500V, 3P+N+PE | Size: 530×320×200mm | Weight: 43.55kg" },
      { name: "20kW Model", value: "TA-DC-WDM 20kW", description: "Output: 20kW | Voltage: 200-1000V | Current: 0-60A | Input: 280-500V, 3P+N+PE | Size: 530×320×200mm | Weight: 44.95kg" },
      { name: "30kW Model", value: "TA-DC-WDM 30kW", description: "Output: 30kW | Voltage: 200-1000V | Current: 0-100A | Input: 280-500V, 3P+N+PE | Size: 550×370×210mm | Weight: 50kg" },
      { name: "40kW Model", value: "TA-DC-WDM 40kW", description: "Output: 40kW | Voltage: 200-1000V | Current: 0-133A | Input: 280-500V, 3P+N+PE | Size: 550×370×210mm | Weight: 60kg" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-WDM" },
      { label: "Output Power", value: "7kW / 15kW / 20kW / 30kW / 40kW" },
      { label: "Output Voltage", value: "50-750V (7kW) / 200-1000V (15-40kW)" },
      { label: "Input Voltage", value: "100-280V (7kW) / 280-500V (15-40kW)" },
      { label: "Output Current", value: "0-20A (7kW) / 0-60A (15-20kW) / 0-100A (30kW) / 0-133A (40kW)" },
      { label: "Display", value: "5-inch color touch screen" },
      { label: "IP Rating", value: "IP54" },
      { label: "Gun Cable Length", value: "5M (customizable)" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Interface Standard", value: "CCS1, CCS2, GB/T, CHAdeMO" },
      { label: "Charging Mode", value: "Plug & charge, RFID card, APP, OCPP" },
    ],
    features: [
      "Premium curved-body design for modern aesthetics",
      "5-inch color touch screen display",
      "Supports CCS1, CCS2, GB/T, and CHAdeMO",
      "Plug-and-charge with RFID card and APP control",
      "OCPP 1.6 compliant for remote management",
      "Optional load balancing for smart grid integration",
      "IP54 rated for indoor and outdoor use",
      "Lightweight and compact wall-mount form factor",
      "Wide power range: 7kW to 40kW",
      "Sleek contours complement contemporary architecture",
    ],
  },
  "ev-dc-dd": {
    description: "TA-DC-DD — 40kW to 80kW dual-gun floor-standing DC fast charger. Robust design for public and commercial charging stations. Supports CCS1, CCS2, GB/T, and CHAdeMO connectors. Features 7-inch touch display, RFID card, APP, OCPP, and load balancing. IP54 rated with forced air cooling. Ideal for public parking lots, shopping centers, and fleet operations.",
    variations: [
      { name: "40kW Model", value: "TA-DC-DD 40kW", description: "Output: 40kW | Voltage: 200-1000V | Current: 0-133A | Input: 285-475V, 63A | Size: 1494×690×350mm | Weight: 168kg" },
      { name: "60kW Model", value: "TA-DC-DD 60kW", description: "Output: 60kW | Voltage: 200-1000V | Current: 0-200A | Input: 260-530V, 105A | Size: 1494×690×350mm | Weight: 211kg" },
      { name: "80kW Model", value: "TA-DC-DD 80kW", description: "Output: 80kW | Voltage: 200-1000V | Current: 0-200A | Input: 260-530V, 130A | Size: 1494×690×350mm | Weight: 236kg" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-DD" },
      { label: "Output Power", value: "40kW / 60kW / 80kW" },
      { label: "Output Voltage", value: "200-1000V" },
      { label: "Input Voltage", value: "285-475V (40kW) / 260-530V (60-80kW)" },
      { label: "Output Current", value: "0-133A (40kW) / 0-200A (60-80kW)" },
      { label: "Input Connection", value: "3P+N+PE" },
      { label: "Dimensions", value: "1494×690×350mm" },
      { label: "Display", value: "7-inch touch screen" },
      { label: "IP Rating", value: "IP54" },
      { label: "Gun Cable Length", value: "5M (customizable)" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Interface Standard", value: "CCS1, CCS2, GB/T, CHAdeMO" },
      { label: "Charging Mode", value: "RFID card, APP, OCPP, load balancing" },
    ],
    features: [
      "Dual-gun simultaneous charging capability",
      "7-inch touch screen with intuitive interface",
      "Supports CCS1, CCS2, GB/T, and CHAdeMO",
      "RFID card, APP, and OCPP charging modes",
      "Load balancing for optimal power distribution",
      "IP54 rated for all-weather outdoor operation",
      "Robust floor-standing design for high-traffic sites",
      "40kW to 80kW power range",
      "Forced air cooling for reliable continuous operation",
      "Comprehensive protection: overvoltage, overcurrent, short-circuit, leakage",
    ],
  },
  "ev-dc-fd": {
    description: "TA-DC-FD — 60kW to 120kW cabinet-type floor-standing DC fast charger with one or two guns (CCS-1/CCS-2/CHAdeMO/GBT). Features 7-inch color touch screen, quick/slow charge automatic switch, swipe card/APP/manual operation. IP54 rated. Built for high-traffic public charging stations, commercial complexes, and highway service areas. CAN/485 standard with optional Ethernet/GPRS/4G networking.",
    variations: [
      { name: "60kW Model", value: "TA-DC-60FD", description: "Output: 60kW | Voltage: 200-1000V | Current: 133A | Input: AC380V±20%, 116A | Size: 730×500×1700mm | Weight: 170kg" },
      { name: "80kW Model", value: "TA-DC-80FD", description: "Output: 80kW | Voltage: 200-1000V | Current: 200A | Input: AC380V±20%, 125A | Size: 730×500×1700mm | Weight: 190kg" },
      { name: "120kW Model", value: "TA-DC-120FD", description: "Output: 120kW | Voltage: 200-1000V | Current: 0-250A | Input: AC380V±20%, 190A | Size: 730×500×1700mm | Weight: 230kg" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-FD (60/80/120kW)" },
      { label: "Output Power", value: "60kW / 80kW / 120kW" },
      { label: "Output Voltage", value: "200-1000V" },
      { label: "Input Voltage", value: "AC380V ±20%" },
      { label: "Output Current", value: "133A (60kW) / 200A (80kW) / 0-250A (120kW)" },
      { label: "Frequency", value: "50/60 Hz" },
      { label: "Dimensions", value: "730×500×1700mm" },
      { label: "Display", value: "7-inch color touch screen" },
      { label: "IP Rating", value: "IP54" },
      { label: "Gun Quantity", value: "One or Two (CCS-1/CCS-2/CHAdeMO/GBT)" },
      { label: "Operating Temperature", value: "-20°C to +50°C" },
      { label: "Altitude", value: "2000M" },
      { label: "Humidity", value: "RH ≤95%" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Network", value: "CAN/485 (standard) / Ethernet, GPRS/4G (optional)" },
    ],
    features: [
      "Cabinet-type design for professional commercial installations",
      "7-inch color touch screen interface",
      "Quick/slow charge automatic switching",
      "Supports CCS1, CCS2, CHAdeMO, and GB/T connectors",
      "Swipe card, APP, and manual charging modes",
      "60kW to 120kW high-power range",
      "IP54 weatherproof rating",
      "CAN/485 standard with optional Ethernet/GPRS/4G",
      "Operating temperature: -20°C to +50°C",
      "Efficiency ≥93% with comprehensive protection systems",
    ],
  },
  "ev-dc-fq-60": {
    description: "TA-DC-FQ — 60kW to 80kW floor-standing dual-gun DC fast charger. Supports CCS1, CCS2, GB/T, and CHAdeMO connectors. Ideal for medium-traffic public charging stations and commercial parking. Features RFID card, APP, and OCPP management with load balancing capability. IP54 rated for reliable outdoor operation.",
    variations: [
      { name: "60kW Model", value: "TA-DC-FQ 60kW", description: "Output: 60kW | Dual-gun DC fast charging | CCS1/CCS2/CHAdeMO/GB/T" },
      { name: "80kW Model", value: "TA-DC-FQ 80kW", description: "Output: 80kW | Dual-gun DC fast charging | CCS1/CCS2/CHAdeMO/GB/T" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-FQ (60-80kW)" },
      { label: "Output Power", value: "60kW / 80kW" },
      { label: "Output Voltage", value: "200-1000V" },
      { label: "IP Rating", value: "IP54" },
      { label: "Interface Standard", value: "CCS1, CCS2, GB/T, CHAdeMO" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Charging Mode", value: "RFID card, APP, OCPP" },
    ],
    features: [
      "Dual-gun floor-standing design",
      "60kW to 80kW medium-power charging",
      "Supports CCS1, CCS2, CHAdeMO, and GB/T",
      "RFID card and APP charging modes",
      "OCPP 1.6 compliant",
      "IP54 rated for outdoor installation",
      "Load balancing support",
      "Ideal for public stations and commercial parking",
    ],
  },
  "ev-dc-fq-120": {
    description: "TA-DC-FQ — 120kW to 180kW floor-standing dual-gun DC fast charger. High-power charging solution for heavy-traffic sites. Supports CCS1, CCS2, GB/T, and CHAdeMO connectors. Designed for public charging hubs, highway rest areas, and commercial fleet operations requiring rapid vehicle turnaround.",
    variations: [
      { name: "120kW Model", value: "TA-DC-FQ 120kW", description: "Output: 120kW | Dual-gun DC fast charging | CCS1/CCS2/CHAdeMO/GB/T" },
      { name: "160kW Model", value: "TA-DC-FQ 160kW", description: "Output: 160kW | Dual-gun DC fast charging | CCS1/CCS2/CHAdeMO/GB/T" },
      { name: "180kW Model", value: "TA-DC-FQ 180kW", description: "Output: 180kW | Dual-gun DC fast charging | CCS1/CCS2/CHAdeMO/GB/T" },
    ],
    specifications: [
      { label: "Model", value: "TA-DC-FQ (120-180kW)" },
      { label: "Output Power", value: "120kW / 160kW / 180kW" },
      { label: "Output Voltage", value: "200-1000V" },
      { label: "IP Rating", value: "IP54" },
      { label: "Interface Standard", value: "CCS1, CCS2, GB/T, CHAdeMO" },
      { label: "Charging Protocol", value: "GBT27930 / CHADEMO 2.0 / DIN 70121 OCPP 1.6(JSON) / ISO 15118" },
      { label: "Charging Mode", value: "RFID card, APP, OCPP" },
    ],
    features: [
      "High-power 120kW to 180kW DC fast charging",
      "Dual-gun floor-standing design",
      "Supports CCS1, CCS2, CHAdeMO, and GB/T",
      "RFID card and APP charging modes",
      "OCPP 1.6 compliant for remote management",
      "IP54 rated for all-weather operation",
      "Ideal for highway rest areas and charging hubs",
      "Rapid vehicle turnaround for fleet operations",
      "Load balancing and smart power distribution",
    ],
  },
  "solar-street-f2l": {
    description: "Integrated solar street light featuring all-in-one design with high-efficiency monocrystalline solar panel, intelligent LED lighting, and advanced battery management system. Available in four models (F2-050, F2-080, F2-100, F2-120) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "Integrated Light" },
      {
        name: "F2-050 Model",
        value: "50W LED, 100W Solar Panel",
        description: "LED: 50W | Size: 1319×460×60mm | Battery: 12.8V 45Ah | Solar Panel: 100W | Pole Height: 8m",
        image: "/Product/StreetLamp/f50.png",
      },
      {
        name: "F2-080 Model",
        value: "80W LED, 160W Solar Panel",
        description: "LED: 80W | Size: 1490×640×60mm | Battery: 25.6V 45Ah | Solar Panel: 160W | Pole Height: 9m",
        image: "/Product/StreetLamp/f80.png",
      },
      {
        name: "F2-100 Model",
        value: "100W LED, 200W Solar Panel",
        description: "LED: 100W | Size: 1490×730×60mm | Battery: 25.6V 52Ah | Solar Panel: 200W | Pole Height: 10m",
        image: "/Product/StreetLamp/f100.png",
      },
      {
        name: "F2-120 Model",
        value: "120W LED, 240W Solar Panel",
        description: "LED: 120W | Size: 1650×830×60mm | Battery: 25.6V 60Ah | Solar Panel: 240W | Pole Height: 12m",
        image: "/Product/StreetLamp/f120.png",
      },
      { name: "LED Power", value: "50W (F2-050) / 80W (F2-080) / 100W (F2-100) / 120W (F2-120)" },
      { name: "Solar Panel", value: "100W (F2-050) / 160W (F2-080) / 200W (F2-100) / 240W (F2-120)" },
      { name: "Battery Capacity", value: "12.8V 45Ah (F2-050) / 25.6V 45Ah (F2-080) / 25.6V 52Ah (F2-100) / 25.6V 60Ah (F2-120)" },
      { name: "Pole Height", value: "8m (F2-050) / 9m (F2-080) / 10m (F2-100) / 12m (F2-120)" },
    ],
    specifications: [
      { label: "Item No.", value: "F2-050 / F2-080 / F2-100 / F2-120" },
      { label: "LED Power", value: "50W / 80W / 100W / 120W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "100W / 160W / 200W / 240W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "12.8V 45Ah (F2-050) / 25.6V 45Ah (F2-080) / 25.6V 52Ah (F2-100) / 25.6V 60Ah (F2-120)" },
      { label: "Equipment Size", value: "1319×460×60mm (F2-050) / 1490×640×60mm (F2-080) / 1490×730×60mm (F2-100) / 1650×830×60mm (F2-120)" },
      { label: "Pole Height", value: "8m / 9m / 10m / 12m" },
      { label: "Working Time", value: "All night lighting, 365 days per year (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP67 (Super waterproof design)" },
      { label: "Battery Material", value: "LFP high-temperature resistant material" },
      { label: "Optical Lens", value: "Polycarbonate (PC) outdoor optical lenses" },
      { label: "Safety Protection", value: "Two hardware protections + one software protection" },
    ],
    features: [
      "Precision grade high-quality aluminum alloy die-casting, patented private molds",
      "Integrated design, modular production, and one click installation",
      "Easy installation, no need for wiring, and no worries about power outages and restrictions",
      "LiFePo4 Lithium battery adopted, with reliable quality and long service life",
      "Adopting high-efficiency LED, with a long service life",
      "All night lighting, resistant to high and low temperatures",
      "Using polycarbonate (PC) outdoor optical lenses - High light transmittance, high temperature resistance, aging resistance, no deformation",
      "LFP high-temperature resistant material, with strong safety performance",
      "New material system, ultra long service life",
      "Two hardware protections + one software protection",
      "Protection level IP67, super waterproof design",
      "Integrated PACK process",
      "Anti rainy, with lights on every night for 365 days",
      "Four power variants: 50W, 80W, 100W, 120W LED",
      "High-efficiency monocrystalline solar panels",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
    ],
  },
  "smart-home-smp2": {
    description: "Compact 5.3kWh residential energy storage system designed for home backup power. Perfect for keeping essential loads running during grid outages. Can run 1 HP aircon (~750W) plus lights, fans, TV, laptop, and phone charging simultaneously. With average 1kW draw, provides approximately 4-5 hours of usable runtime. Ideal for backup power during brownouts, sari-sari store lighting with small freezer, off-grid tiny homes, farm huts, and construction site offices. Includes 4×670W solar panels (2.68kW total) for solar charging capability. Perfect for basic rural homes (no AC) or as backup power solution.",
    variations: [
      { name: "Capacity", value: "5.3kWh" },
      { name: "Rated Power", value: "3kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 4 panels (2.68kW total)" },
      { name: "Can Run At Once", value: "1 HP aircon (~750W) plus lights, fans, TV, laptop, phone charging" },
      { name: "Runtime Example", value: "If you draw around 1kW on average → about 4-5 hours usable" },
      { name: "Typical Uses", value: "Backup power for small houses during brownouts; Sari-sari store lights + small freezer for a few hours; Off-grid tiny homes, farm huts, and construction site office; Basic rural home (no AC)" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "3kW / AC 220V" },
      { label: "Battery Capacity", value: "5.3kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 4 panels (2.68kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "3kW" },
      { label: "Typical Runtime", value: "4-5 hours at 1kW average load" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp3": {
    description: "10kWh / 5kW residential energy storage system designed for standard homes and small businesses. Perfect for urban homes that want backup for long brownouts. Can run 1-2 HP aircon, refrigerator, lights, fans, TV, and computers simultaneously. With average 1.5-2kW draw, provides approximately 5-6 hours of usable runtime. Ideal for small clinics, small offices, BPO satellite offices, internet cafés, small resort cottages, and Airbnb units. Includes 6×670W solar panels (4.02kW total) for solar charging capability. Perfect for middle-class homes with 1-2 AC units.",
    variations: [
      { name: "Capacity", value: "10.6kWh" },
      { name: "Rated Power", value: "5kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 6 panels (4.02kW total)" },
      { name: "Can Run At Once", value: "1-2 HP aircon, Refrigerator, Lights, fans, TV, computers" },
      { name: "Runtime Example", value: "If house averages 1.5-2kW → around 5-6 hours usable" },
      { name: "Typical Uses", value: "Urban homes that want backup for long brownouts; Small clinics, small offices, BPO satellite office, internet café; Small resort cottage / Airbnb unit" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "5kW / AC 220V" },
      { label: "Battery Capacity", value: "10.6kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 6 panels (4.02kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "5kW" },
      { label: "Typical Runtime", value: "5-6 hours at 1.5-2kW average load" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp4": {
    description: "15kWh / 5kW residential energy storage system with longer backup duration and same power output as 10kWh model. Same maximum power (5kW) as the 10kWh, but with a larger battery for extended runtime. Perfect for appliances similar to a 10kWh user, but when brownouts last much longer. Ideal for rural homes with frequent long outages, stores with freezers (meat, ice cream) that must stay cold overnight, and small cell sites/telecom repeaters wanting longer autonomy. Includes 8×670W solar panels (5.36kW total) for solar charging capability.",
    variations: [
      { name: "Capacity", value: "15.9kWh" },
      { name: "Rated Power", value: "5kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 8 panels (5.36kW total)" },
      { name: "Can Run At Once", value: "1-2 HP aircon, Refrigerator, Lights, fans, TV, computers (same as 10kWh)" },
      { name: "Runtime Example", value: "Longer backup duration compared to 10kWh model for extended brownouts" },
      { name: "Typical Uses", value: "Rural homes with frequent long outages; Stores with freezers (meat, ice cream) that must stay cold overnight; Small cell sites/telecom repeaters wanting longer autonomy" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "5kW / AC 220V" },
      { label: "Battery Capacity", value: "15.9kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 8 panels (5.36kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "5kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp5": {
    description: "20kWh / 10kW residential and commercial energy storage system with double advantage: bigger battery + higher power (10kW). Perfect for larger homes and small commercial applications. Can run multiple aircons (3-4 HP total), refrigerator/freezer, lights, computers, pumps, etc., as long as total load is under 10kW. Ideal for large homes with multiple AC units, small resorts or beach houses (several rooms + common area), restaurants, bakeries, and small manufacturing with light machinery, and community facilities like barangay halls, schools, classrooms, and evacuation centers. Includes 12×670W solar panels (8.04kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "21.2kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 12 panels (8.04kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Typical Uses", value: "Large homes with multiple AC units; Small resorts or beach houses (several rooms + common area); Restaurants, bakeries, and small manufacturing with light machinery; Community facilities: barangay halls, schools, classrooms, and evacuation centers" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "21.2kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 12 panels (8.04kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp6": {
    description: "25kWh / 10kW residential and commercial energy storage system with more hours and same power. Same 10kW limit but longer-lasting storage. Perfect when you need a full day-night cycle backup for moderate loads. Ideal for off-grid homes or lodges that must run all night, cold storage rooms for small agri businesses, and small hospitals/clinics needing longer uptime for equipment (but still small scale). Includes 14×670W solar panels (9.38kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "26.5kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 14 panels (9.38kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Runtime Example", value: "Full day-night cycle backup for moderate loads" },
      { name: "Typical Uses", value: "Off-grid homes or lodges that must run all night; Cold storage rooms for small agri businesses; Small hospitals/clinics needing longer uptime for equipment" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "26.5kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 14 panels (9.38kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp7": {
    description: "30kWh / 10kW mini-microgrid energy storage system. Max 10kW output, but the biggest tank of energy in this list. If the average load is 2-3kW, can often run through the night. Ideal for off-grid communities (several houses sharing one system), remote resorts, island communities, telecom towers + equipment shelters, and farms with pumps, cold storage, and house all in one system. Includes 16×670W solar panels (10.72kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "31.8kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 16 panels (10.72kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Runtime Example", value: "If average load is 2-3kW → can often run through the night" },
      { name: "Typical Uses", value: "Off-grid communities (several houses sharing one system); Remote resorts, island communities; Telecom towers + equipment shelters; Farms with pumps, cold storage, and house all in one system" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "31.8kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 16 panels (10.72kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "cabinet-14": {
    description: "Village / industrial-scale cabinet-type energy storage system (215-261 kWh / 100-110 kW). Serious microgrids that can supply tens of houses plus businesses, or one small industrial plant (rice mill complex, ice plant, food processing, shipyard section). Ideal for whole small islands / sitios (dozens of households), LGU projects (solarizing barangays, ports, fish landing centers), and large commercial farms, cold-storage hubs, ice plants. Big models (215-261 kWh, 100-110 kW) suitable for whole small community or industrial site. Includes 144×670W solar panels (96.48kW total) for solar charging capability.",
    variations: [
      { 
        name: "215kWh / 100kW", 
        value: "Village / Industrial-Scale Microgrid",
        description: "215.04kWh battery, 100kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Can supply tens of houses plus businesses, or one small industrial plant.",
        image: "/Product/cabinet/cb14/215.png"
      },
      { 
        name: "233kWh / 110kW", 
        value: "Advanced Village / Industrial-Scale Microgrid",
        description: "232.9kWh battery, 110kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Enhanced capacity for whole small communities or industrial sites.",
        image: "/Product/cabinet/cb14/233.png"
      },
      { 
        name: "261kWh / 110kW", 
        value: "Maximum Capacity Village / Industrial-Scale Microgrid",
        description: "261.2kWh battery, 110kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Maximum capacity for the most demanding village or industrial applications.",
        image: "/Product/cabinet/cb14/261.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Can Power", value: "Tens of houses plus businesses, or one small industrial plant (rice mill complex, ice plant, food processing, shipyard section)" },
      { name: "Typical Uses", value: "Whole small islands / sitios (dozens of households); LGU projects (solarizing barangays, ports, fish landing centers); Large commercial farms, cold-storage hubs, ice plants" },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Big models (215-261 kWh, 100-110 kW) → whole small community or industrial site." },
    ],
    specifications: [
      { label: "Rated Power", value: "100kW / 110kW (AC)" },
      { label: "Battery Capacity", value: "215.04kWh / 232.9kWh / 261.2kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 144 panels (96.48kW total)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Serious microgrid capability for village/industrial scale",
      "Can supply tens of houses plus businesses",
      "Perfect for whole small islands / sitios (dozens of households)",
      "Ideal for LGU projects (solarizing barangays, ports, fish landing centers)",
      "Suitable for large commercial farms, cold-storage hubs, ice plants",
      "Can power one small industrial plant (rice mill, ice plant, food processing, shipyard)",
      "Includes 144×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Village / industrial-scale microgrid solution",
    ],
  },
  "cabinet-15": {
    description: "Large-scale industrial / community microgrid cabinet-type energy storage system (466-522 kWh / 220 kW). Ultra-high capacity and power output for large-scale operations. Can power large industrial complexes, multiple commercial facilities, or entire communities. Ideal for utility-scale applications, large manufacturing facilities, and major infrastructure projects requiring massive energy storage capacity.",
    variations: [
      { 
        name: "466kWh / 220kW", 
        value: "Large-Scale Industrial / Community Microgrid",
        description: "465.8kWh battery, 220kW rated power, 400V/220V output. Includes 288×670W solar panels (192.96kW total). Ultra-high capacity for large-scale industrial and community applications.",
        image: "/Product/cabinet/cb15/466.png"
      },
      { 
        name: "522kWh / 220kW", 
        value: "Maximum Capacity Industrial / Community Microgrid",
        description: "522.4kWh battery, 220kW rated power, 400V/220V output. Includes 288×670W solar panels (192.96kW total). Maximum capacity for the most demanding large-scale applications.",
        image: "/Product/cabinet/cb15/522.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "220kW (AC)" },
      { label: "Battery Capacity", value: "465.8kWh / 522.4kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 288 panels (192.96kW)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Ultra-high capacity for large-scale operations",
      "Perfect for large industrial complexes and multiple commercial facilities",
      "Ideal for utility-scale applications and major infrastructure projects",
      "Suitable for entire communities requiring massive energy storage",
      "Includes 288-444×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Large-scale industrial / community microgrid solution",
    ],
  },
  "cabinet-16": {
    description: "Village or island grid cabinet-type energy storage system (783 kWh / 300 kW). Can act as the main power plant for a whole small island barangay with a few hundred households, a school, a clinic, and small businesses; a large resort complex with multiple buildings, pools, restaurants, and laundry; or a cluster of factories (e.g., agro-processing complex). At 150kW average load, provides around 5 hours of storage; with solar, this can cover day + part of night. Includes 444×670W solar panels (297.48kW total) for solar charging capability.",
    variations: [
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Can Act As", value: "Main power plant for: whole small island barangay with a few hundred households, a school, a clinic, and small businesses; large resort complex with multiple buildings, pools, restaurants, and laundry; cluster of factories (e.g., agro-processing complex)" },
      { name: "Battery Runtime", value: "At 150kW average → around 5 hours of storage; with solar, this can cover day + part of night" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "300kW (AC)" },
      { label: "Battery Capacity", value: "783.6kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 444 panels (297.48kW total)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Can act as main power plant for whole small island barangays",
      "Perfect for large resort complexes with multiple buildings",
      "Ideal for clusters of factories and agro-processing complexes",
      "At 150kW average load, provides around 5 hours of storage",
      "With solar, can cover day + part of night",
      "Includes 444×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Village or island grid solution",
    ],
  },
  "cabinet-item4": {
    description: "Cabinet-type energy storage system for commercial and industrial facility applications. Available in multiple capacity options from 40kWh to 100kWh. Can power 5-10 small houses, or a water refilling station, rice mill, small cold room, plus office & lighting, or a cell tower + equipment shelter with extra capacity. Ideal for off-grid tourist sites with a few cottages, poultry/piggery/fish farms (lighting, blowers, small machinery), and telecom sites that want to reduce diesel use.",
    variations: [
      { 
        name: "40kWh / 20kW", 
        value: "Small Commercial / Remote Facility",
        description: "40.96kWh battery, 20kW rated power, 380V/220V output. Includes 30×670W solar panels (20.1kW total). Can power: 5-10 small houses, or a water refilling station, rice mill, small cold room, plus office & lighting, or a cell tower + equipment shelter with extra capacity. Market: Off-grid tourist sites with a few cottages, poultry/piggery/fish farms (lighting, blowers, small machinery), telecom sites that want to reduce diesel use.",
        image: "/Product/cabinet/20.png"
      },
      { 
        name: "60kWh / 30kW", 
        value: "Small Community or Larger Business",
        description: "61.4kWh battery, 30kW rated power, 380V/220V output. Includes 40×670W solar panels (26.8kW total). Can power: a small resort (10+ rooms, kitchen, bar, pool pump), a medium agricultural facility (irrigation pumps, storage, office), or a cluster of 10-20 households with controlled use. Market: Island barangays, remote mountain communities, bigger manufacturing workshops (welding, small machines).",
        image: "/Product/cabinet/30.png"
      },
      { 
        name: "80kWh / 40kW", 
        value: "Microgrid for a Barangay Center or Campus",
        description: "83.2kWh battery, 40kW rated power, 380V/220V output. Includes 60×670W solar panels (40.2kW total). Suitable for: school campus (several buildings, lights, fans, computers), barangay center + streetlights + market area, or medium resort or eco-park with many cottages plus common facilities. Good where diesel gensets are currently used daily, and fuel is expensive. Many loads are running at the same time (kitchen, laundry, ACs, pumps).",
        image: "/Product/cabinet/40.png"
      },
      { 
        name: "100kWh / 50kW", 
        value: "Microgrid for a Barangay Center or Campus",
        description: "100.3kWh battery, 50kW rated power, 380V/220V output. Includes 72×670W solar panels (48.24kW total). Suitable for: school campus (several buildings, lights, fans, computers), barangay center + streetlights + market area, or medium resort or eco-park with many cottages plus common facilities. Good where diesel gensets are currently used daily, and fuel is expensive. Many loads are running at the same time (kitchen, laundry, ACs, pumps).",
        image: "/Product/cabinet/50.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Model Size", value: "Smaller models (40-60 kWh, 20-30 kW) → single business or small compound. Mid models (80-100 kWh, 40-50 kW) → school, resort, or barangay center." },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 380/400V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "20kW / 30kW / 40kW / 50kW (AC)" },
      { label: "Battery Capacity", value: "40.96kWh / 61.4kWh / 83.2kWh / 100.3kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 30-72 panels (20.1kW - 48.24kW total)" },
      { label: "Voltage", value: "380V / 220V" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Can power 5-10 small houses or commercial facilities",
      "Perfect for off-grid tourist sites and remote facilities",
      "Ideal for agricultural and farming applications",
      "Suitable for telecom sites reducing diesel dependency",
      "Includes 30-72×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Mini power plant/microgrid capability",
    ],
  },
  "solar-street-rklv02": {
    description: "Road King-LV02 compact solar street lighting system featuring split design with separate solar panel and LED fixture. Available in multiple models with varying power outputs, pole heights, and battery capacities to suit different lighting requirements. Includes both Split Street Light and All in Two Light configurations.",
    variations: [
      { name: "Light Type", value: "Split Street Light" },
      {
        name: "LVQ2-050 Model",
        value: "50W LED, 100W Solar Panel",
        description: "LED: 50W | Size: 935×415×210mm | Battery: 14.8V 45Ah | Solar Panel: 100W | Pole Height: 8m",
        image: "/Product/StreetLamp/lvq2/l50.png",
      },
      {
        name: "LVQ2-080 Model",
        value: "80W LED, 200W Solar Panel",
        description: "LED: 80W | Size: 935×415×210mm | Battery: 12.8V 90Ah | Solar Panel: 200W | Pole Height: 9m",
        image: "/Product/StreetLamp/lvq2/l80.png",
      },
      {
        name: "LVQ2-100 Model",
        value: "100W LED, 250W Solar Panel",
        description: "LED: 100W | Size: 935×415×210mm | Battery: 25.6V 48Ah | Solar Panel: 250W | Pole Height: 10m",
        image: "/Product/StreetLamp/lvq2/l100.png",
      },
      {
        name: "LVQ2-120 Model",
        value: "120W LED, 300W Solar Panel",
        description: "LED: 120W | Size: 935×415×210mm | Battery: 25.6V 60Ah | Solar Panel: 300W | Pole Height: 12m",
        image: "/Product/StreetLamp/lvq2/l120.png",
      },
      { name: "LED Power", value: "50W (LVQ2-050) / 80W (LVQ2-080) / 100W (LVQ2-100) / 120W (LVQ2-120)" },
      { name: "Solar Panel", value: "100W (LVQ2-050) / 200W (LVQ2-080) / 250W (LVQ2-100) / 300W (LVQ2-120)" },
      { name: "Battery Capacity", value: "14.8V 45Ah (LVQ2-050) / 12.8V 90Ah (LVQ2-080) / 25.6V 48Ah (LVQ2-100) / 25.6V 60Ah (LVQ2-120)" },
      { name: "Pole Height", value: "8m (LVQ2-050) / 9m (LVQ2-080) / 10m (LVQ2-100) / 12m (LVQ2-120)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVQ2-050 / LVQ2-080 / LVQ2-100 / LVQ2-120" },
      { label: "LED Power", value: "50W / 80W / 100W / 120W (Split)" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "100W / 200W / 250W / 300W (Split)" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "14.8V 45Ah (LVQ2-050) / 12.8V 90Ah (LVQ2-080) / 25.6V 48Ah (LVQ2-100) / 25.6V 60Ah (LVQ2-120)" },
      { label: "Equipment Size", value: "935×415×210mm (LVQ2 series)" },
      { label: "Pole Height", value: "8m / 9m / 10m / 12m (Split)" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "Split Street Light design with separate solar panel and LED fixture",
      "All in Two Light integrated design option",
      "Multiple power variants: 20W, 30W, 80W, 100W, 120W LED",
      "High-efficiency monocrystalline solar panels",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
    ],
  },
  "solar-street-rks": {
    description: "Solar Road King Series LVXC2 premium solar street lighting solution featuring all-in-two design with integrated solar panel and LED fixture. Available in two models (LVXC-320, LVXC-330) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "All in Two Light" },
      {
        name: "LVXC-120 Model",
        value: "20W LED, 70W Solar Panel",
        description: "LED: 20W | Size: 495×205×80mm | Battery: 3.2V 65Ah | Solar Panel: 70W | Pole Height: 5m",
        image: "/Product/StreetLamp/lvxc2/c120.png",
      },
      {
        name: "LVXC-130 Model",
        value: "30W LED, 70W Solar Panel",
        description: "LED: 30W | Size: 550×240×100mm | Battery: 3.2V 80Ah | Solar Panel: 70W | Pole Height: 6m",
        image: "/Product/StreetLamp/lvxc2/c130.png",
      },
      { name: "LED Power", value: "20W (LVXC-120) / 30W (LVXC-130)" },
      { name: "Solar Panel", value: "70W (LVXC-120/130)" },
      { name: "Battery Capacity", value: "3.2V 65Ah (LVXC-120) / 3.2V 80Ah (LVXC-130)" },
      { name: "Pole Height", value: "5m (LVXC-120) / 6m (LVXC-130)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVXC-120 / LVXC-130" },
      { label: "LED Power", value: "20W / 30W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "70W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "3.2V 65Ah (LVXC-120) / 3.2V 80Ah (LVXC-130)" },
      { label: "Equipment Size", value: "495×205×80mm (LVXC-120) / 550×240×100mm (LVXC-130)" },
      { label: "Pole Height", value: "5m / 6m" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "All in Two Light integrated design",
      "Two power variants: 20W and 30W LED",
      "High-efficiency monocrystalline solar panels (70W)",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights (5m/6m)",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
      "Compact sizes: 495×205×80mm (LVXC-120) / 550×240×100mm (LVXC-130)",
    ],
  },
  "solar-street-lvxc": {
    description: "Solar Road King Series LVXC3 high-performance solar street lighting system featuring all-in-two design with integrated solar panel and LED fixture. Available in two models (LVXC-320, LVXC-330) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "All in Two Light" },
      {
        name: "LVXC-320 Model",
        value: "20W LED, 70W Solar Panel",
        description: "LED: 20W | Size: 650×300×130mm | Battery: 3.2V 65Ah | Solar Panel: 70W | Pole Height: 5m",
        image: "/Product/StreetLamp/lvxc3/c320.png",
      },
      {
        name: "LVXC-330 Model",
        value: "30W LED, 70W Solar Panel",
        description: "LED: 30W | Size: 650×300×130mm | Battery: 3.2V 80Ah | Solar Panel: 70W | Pole Height: 6m",
        image: "/Product/StreetLamp/lvxc3/c330.png",
      },
      { name: "LED Power", value: "20W (LVXC-320) / 30W (LVXC-330)" },
      { name: "Solar Panel", value: "70W (LVXC-320/330)" },
      { name: "Battery Capacity", value: "3.2V 65Ah (LVXC-320) / 3.2V 80Ah (LVXC-330)" },
      { name: "Pole Height", value: "5m (LVXC-320) / 6m (LVXC-330)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVXC-320 / LVXC-330" },
      { label: "LED Power", value: "20W / 30W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "70W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "3.2V 65Ah (LVXC-320) / 3.2V 80Ah (LVXC-330)" },
      { label: "Equipment Size", value: "650×300×130mm" },
      { label: "Pole Height", value: "5m / 6m" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "All in Two Light integrated design",
      "Two power variants: 20W and 30W LED",
      "High-efficiency monocrystalline solar panels (70W)",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights (5m/6m)",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
      "Compact size: 650×300×130mm",
    ],
  },
  "container-con1": {
    description: "Small utility-level / industrial park containerized Battery Energy Storage System (BESS) and hybrid power system. Designed for significant energy demands equivalent to small utility operations or industrial parks. Available in multiple capacity configurations from 1075kWh to 2700kWh, with rated power options of 500kW or 1000kW AC. Ideal for main power for small island towns (currently using diesel generators), industrial park or export zone tenants (cold-storage hubs, fish ports, mining camps), and large university or hospital campuses or combined municipal loads. When paired with big solar and possibly backup diesel, can provide 24/7 coverage. For average demand of 250-300 kW, provides roughly 3-4 hours of battery at full output. At 150 kW average → around 5 hours of storage; with solar, this can cover day + part of night.",
    variations: [
      {
        name: "1075kWh System",
        value: "500KW/AC, 1075.2kWh Battery, 728×670W Solar Panels",
        description: "Rated Power: 500KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1075.2kWh | Solar Panel: 670W × 728PCS (487.76kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "500kW (AC)" },
          { label: "Battery Capacity", value: "1075.2kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 728 panels (487.76kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "1205kWh System",
        value: "500KW/AC, 1205.76kWh Battery, 728×670W Solar Panels",
        description: "Rated Power: 500KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1205.76kWh | Solar Panel: 670W × 728PCS (487.76kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "500kW (AC)" },
          { label: "Battery Capacity", value: "1205.76kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 728 panels (487.76kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "1800kWh System",
        value: "1000KW/AC, 1806.3kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1806.3kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "1806.3kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2000kWh System",
        value: "1000KW/AC, 2025.67kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2025.67kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2025.67kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2300kWh System",
        value: "1000KW/AC, 2362.28kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2362.28kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2362.28kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2700kWh System",
        value: "1000KW/AC, 2700.9kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2700.9kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2700.9kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      { name: "Available Capacities", value: "1075kWh / 1205kWh / 1800kWh / 2000kWh / 2300kWh / 2700kWh" },
      { name: "Rated Power", value: "500KW/AC (1075kWh, 1205kWh) / 1000KW/AC (1800kWh, 2000kWh, 2300kWh, 2700kWh)" },
      { name: "Battery Capacity", value: "1075.2kWh - 2700.9kWh (Lithium Battery)" },
      { name: "Solar Panel", value: "670W × 728-1484 panels (487.76kW - 994.28kW total)" },
      { name: "Voltage", value: "400V/220V" },
      { name: "Included Components", value: "Splice bracket + wiring" },
    ],
    specifications: [
      { label: "Rated Power", value: "500kW / 1000kW (AC)" },
      { label: "Battery Capacity", value: "1075.2kWh - 2700.9kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 728-1484 panels (487kW - 994kW total)" },
      { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
      { label: "Typical Storage", value: "3-6 hours at full output" },
      { label: "Coverage", value: "24/7 with solar + backup diesel" },
    ],
    features: [
      "Small utility-level / industrial park containerized BESS system",
      "Multiple capacity options from 1075kWh to 2700kWh",
      "High power output: 500kW or 1000kW AC",
      "Large-scale solar integration (487kW - 994kW)",
      "Lithium battery technology with advanced BMS",
      "Three-phase + single-phase output (400V/380V + 220V)",
      "24/7 coverage when paired with solar + backup diesel",
      "3-6 hours of battery storage at full output",
      "Complete system with splice bracket and wiring",
      "Ideal for small island towns replacing diesel generators",
      "Suitable for industrial parks, export zones, and mining camps",
      "Perfect for large university or hospital campuses",
      "Containerized design for easy deployment and relocation",
      "Scalable solution for utility-scale energy storage",
    ],
  },
};

