export type ProductCategory =
  | "all"
  | "ev-charging"
  | "solar-street"
  | "smart-home"
  | "cabinet"
  // | "container"
  ;

export type ProductVariation = {
  name: string;
  value: string;
  description?: string;
  price?: string; // Optional price for this variation
  image?: string; // Optional image for this variation
  specifications?: { label: string; value: string }[]; // Optional specifications for this variation
};

export type ProductLayout = "ev" | "b2b" | "auto"; // "auto" uses category-based default

export type Product = {
  id: string;
  name: string;
  subtitle: string;
  category: ProductCategory;
  tag?: string;
  image: string;
  images?: string[]; // Additional images for gallery
  price?: string; // Product price
  description?: string;
  variations?: ProductVariation[];
  specifications?: { label: string; value: string }[];
  features?: string[];
  layout?: ProductLayout; // Optional: specify which layout to use ("ev" or "b2b"), defaults to "auto" (category-based)
};

export const categories: { id: ProductCategory; label: string }[] = [
  { id: "all", label: "All Products" },
  { id: "ev-charging", label: "EV Charging Station" },
  { id: "solar-street", label: "Solar Street Lights" },
  { id: "smart-home", label: "Smart Home IPS" },
  { id: "cabinet", label: "Power Supplies" },
  // { id: "container", label: "Container Type Power Supply" },
];

export const categoryBanner: Record<
  ProductCategory,
  { title: string; description: string; image: string; video?: string }
> = {
  all: {
    title: "Energy Storage & Power Products",
    description:
      "From EV charging to smart home backup and utility-scale storage, VoltHub delivers trusted, safe and efficient power for every scenario.",
    image: "/resources/bulb.jpg",
  },
  "ev-charging": {
    title: "EV Charging Station Solutions",
    description:
      "Fast, reliable EV charging systems for homes, fleets and public sites, with smart monitoring and billing.",
    image: "/resources/charging-stats.jpg",
  },
  "solar-street": {
    title: "Solar Street Lighting Systems",
    description:
      "High‑efficiency solar street lights with intelligent control, built for streets, campuses and industrial parks.",
    image: "/aboutimages/solarstreetlight.jpg",
  },
  "smart-home": {
    title: "Smart Home IPS Backup",
    description:
      "Compact indoor power systems that keep your essential loads running during grid outages.",
    image: "/HomeBanner/homebatt.png",
    video: "/Product/SMVB.mp4",
  },
  cabinet: {
    title: "Power Supplies",
    description:
      "Modular cabinet energy storage and power supply systems for commercial and industrial applications.",
    image: "/resources/power-grid.jpg",
   // video: "/Product/CNvB.mp4",
  },
  // container: {
  //   title: "Container Type Power Supply",
  //   description:
  //     "Utility‑scale containerized BESS and hybrid power systems ready for rapid deployment.",
  //   image: "/HomeBanner/container.png",
  //   video: "/Product/CBMB.mp4",
  // },
};

// Based on Absen Energy products layout, adapted to VoltHub
// Reference: `https://www.absenenergy.com/en/product/`
export const products: Product[] = [
  // EV Charging Station products
  {
    id: "ev-charging-53",
    name: "DC EV Charger Dual Gun",
    subtitle: "Advanced EV charging solution for commercial and public use",
    category: "ev-charging",
    tag: " Dual-gun DC Charging Pile ",
    image: "/Product/EV/53.png",
    images: ["/Product/EV/53.png", "/Product/EV/yellow/110.png", "/Product/EV/yellow/197.jpg"],
    description: "DPEV-160KM / DPEV-240KM - 160kW / 240kW Dual-Gun DC high-power fast charger. Ideal for premium charging hubs, expressway service areas, and sites serving EVs that support higher charging power. Features single-gun full power or dual-gun current sharing modes. Faster sessions, future-proof for newer EVs.",
  },
  {
    id: "ev-charging-59",
    name: "AC EV Charger 7kW",
    subtitle: "High-performance EV charging system",
    category: "ev-charging",
    tag: " Single-gun AC Charging Pile",
    image: "/Product/EV/59.png",
    images: [
      "/Product/EV/59.png",
      "/Product/EV/small/disc1.png",
      "/Product/EV/small/disc2.png",
      "/Product/EV/small/82.png",
      "/Product/EV/small/173.jpg",
      "/Product/EV/small/192.jpg",
    ],
  },
  {
    id: "ev-charging-64",
    name: "DC EV Charger Single Gun",
    subtitle: "Fast and reliable EV charging solution",
    category: "ev-charging",
    tag: " Dual-gun DC Charging Pile ",
    image: "/Product/EV/64.png",
    images: [
      "/Product/EV/64.png",
      "/Product/EV/red/69.jpg",
      "/Product/EV/red/111.png",
    ],
  },
    {
    id: "ev-charging-89",
    name: "DC EV Charger Dual Gun",
    subtitle: "Premium EV charging station for fleets and public sites",
    category: "ev-charging",
    tag: " Dual-gun DC Charging Pile ",
    image: "/Product/EV/89.png",
    images: [
      "/Product/EV/89.png",
      "/Product/EV/green/58.png",
      "/Product/EV/green/106.jpg",
      "/Product/EV/green/161.jpg",
      "/Product/EV/green/162.jpg",
      "/Product/EV/green/163.jpg",
    ],
    description: "DPEV-60K / DPEV-120K - 60kW / 120kW Dual-Gun DC high-power fast charger. Ideal for premium charging hubs, expressway service areas, and sites serving EVs that support higher charging power. Features single-gun full power or dual-gun current sharing modes. Faster sessions, future-proof for newer EVs.",
  },
  // Solar Street Lights products
//   {
//     id: "solar-street-f1l",
//     name: "F1L Solar Street Light",
//     subtitle: "High-efficiency solar street lighting system",
//     category: "solar-street",
//     tag: "Integrated Light",
//     image: "/Product/StreetLamp/F1L.png",
//   },
  {
    id: "solar-street-f2l",
    name: "Integrated Lamp F2 Series",
    subtitle: "The Light of Energy, Crefted with Ingenuity",
    category: "solar-street",
    tag: "Integrated Light",
    image: "/Product/StreetLamp/F2L.png",
    images: [
      "/Product/StreetLamp/F2L.png",
      "/Product/StreetLamp/f2/prod4.png",
      "/Product/StreetLamp/f2/disc1.png",
      "/Product/StreetLamp/f2/disc2.png",
      "/Product/StreetLamp/f2/disc3.png",
      "/Product/StreetLamp/f2/disc4.png",
      "/Product/StreetLamp/f2/disc5.png",
      "/Product/StreetLamp/f2/disc6.png",
    ],
  },
  {
    id: "solar-street-rklv02",
    name: "Road King-LV02",
    subtitle: "Compact solar street lighting system",
    category: "solar-street",
    tag: "Split Street Light",
    image: "/Product/StreetLamp/RKlv02.png",
    images: [
      "/Product/StreetLamp/RKlv02.png",
      "/Product/StreetLamp/lvxc2/prod1.png",
      "/Product/StreetLamp/lvq2/disc1.png",
      "/Product/StreetLamp/lvq2/disc2.png",
      "/Product/StreetLamp/lvq2/disc3.png",
      "/Product/StreetLamp/lvq2/disc4.png",
      "/Product/StreetLamp/lvq2/disc5.png",
      "/Product/StreetLamp/lvq2/disc6.png",
      "/Product/StreetLamp/lvq2/disc7.png",
    ],
  },
  {
    id: "solar-street-rks",
    name: "Solar Road King Series LVXC2",
    subtitle: "Premium solar street lighting solution",
    category: "solar-street",
    tag: "All in Two Light",
    image: "/Product/StreetLamp/RKS.png",
    images: [
      "/Product/StreetLamp/RKS.png",
      "/Product/StreetLamp/lvq2/prod1.png",
     // "/Product/StreetLamp/lvxc2/disc1.png",
      "/Product/StreetLamp/lvxc2/disc2.png",
      "/Product/StreetLamp/lvxc2/disc3.png",
      "/Product/StreetLamp/lvxc2/disc4.png",
      "/Product/StreetLamp/lvxc2/disc5.png",
      "/Product/StreetLamp/lvxc2/disc6.png",
      "/Product/StreetLamp/lvxc2/disc7.png",
      "/Product/StreetLamp/lvxc2/disc8.png",
    ],
  },
  {
    id: "solar-street-lvxc",
    name: "Solar Road King Series LVXC3",
    subtitle: "High-performance solar street lighting system",
    category: "solar-street",
    tag: "All in Two Light",
    image: "/Product/StreetLamp/LVXC.png",
    images: [
      "/Product/StreetLamp/LVXC.png",
      "/Product/StreetLamp/lvxc3/prod1.png",
   // "/Product/StreetLamp/lvxc3/disc1.png",
      "/Product/StreetLamp/lvxc3/disc2.png",
      "/Product/StreetLamp/lvxc3/disc3.png",
      "/Product/StreetLamp/lvxc3/disc4.png",
      "/Product/StreetLamp/lvxc3/disc5.png",
      "/Product/StreetLamp/lvxc3/disc6.png",
      "/Product/StreetLamp/lvxc3/disc7.png",
      "/Product/StreetLamp/lvxc3/disc8.png",
    ],
  },
  // Smart Home IPS products
  {
    id: "smart-home-smp2",
    name: "Smart Home IPS 5kWh",
    subtitle: "Residential Smart Home Power System",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP2.png",
    images: [
      "/Product/SmartHome/SMP2.png",
      "/Product/SmartHome/2B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp3",
    name: "Smart Home IPS 10kWh",
    subtitle: "Standard Home / Small Business Power System",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP3.png",
    images: [
      "/Product/SmartHome/SMP3.png",
  
      "/Product/SmartHome/3B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp4",
    name: "Smart Home IPS 15kWh",
    subtitle: "Longer Backup, Same Power",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP4.png",
    images: [
      "/Product/SmartHome/SMP4.png",
      "/Product/SmartHome/4B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp5",
    name: "Smart Home IPS 20kWh",
    subtitle: "Larger Home / Small Commercial",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP5.png",
    images: [
      "/Product/SmartHome/SMP5.png",
    
      "/Product/SmartHome/5B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp6",
    name: "Smart Home IPS 25kWh",
    subtitle: "More Hours, Same Power",
    category: "smart-home",
    layout: "ev", // Use EV layout for this product
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP6.png",
    images: [
      "/Product/SmartHome/SMP6.png",
      "/Product/SmartHome/6B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  {
    id: "smart-home-smp7",
    name: "Smart Home IPS 30kWh",
    subtitle: "Mini-Microgrid",
    category: "smart-home",
    tag: "Mobile Energy Storage Power",
    image: "/Product/SmartHome/SMP7.png",
    images: [
      "/Product/SmartHome/SMP7.png",
      "/Product/SmartHome/7B/prodD.png",
      "/Product/SmartHome/2B/prod1.png",
      "/Product/SmartHome/2B/prod2.png",
      "/Product/SmartHome/2B/prod3.png",
      "/Product/SmartHome/2B/prod4.png",
      "/Product/SmartHome/disc3.png",
      "/Product/SmartHome/disc4.png",
    ],
  },
  // Cabinet Type Power Supply products
  {
    id: "cabinet-14",
    name: "Cabinet Type Power Supply 215kWh",
    subtitle: "Village / Industrial-Scale Microgrid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/200kwh.png",
    images: [
      "/Product/cabinet/200kwh.png",
      "/Product/cabinet/cb14/prod2.png",
      "/Product/cabinet/cb14/prod3.png",
      "/Product/cabinet/cb14/prod4.png",
    ],
  },
  {
    id: "cabinet-15",
    name: "Cabinet Type Power Supply 522kWh",
    subtitle: "Large-Scale Industrial / Community Microgrid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/500kwh.png",
    images: [
      "/Product/cabinet/500kwh.png",
      "/Product/cabinet/cb15/prod1.png",
      "/Product/cabinet/cb15/prod2.png",
      "/Product/cabinet/cb14/prod2.png",
    ],
  },
  {
    id: "cabinet-16",
    name: "Cabinet Type Power Supply 783kWh",
    subtitle: "Village or Island Grid",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/700kwh.png",
    images: [
      "/Product/cabinet/700kwh.png",
      "/Product/cabinet/cb16/prod1.png",
      "/Product/cabinet/cb16/prod2.png",
      "/Product/cabinet/cb16/prod3.png",
      "/Product/cabinet/cb14/prod2.png",
    ],
  },
  {
    id: "cabinet-item4",
    name: "Cabinet Type Power Supply 40kWh",
    subtitle: "Small Commercial / Remote Facility",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/cabinet/20.png",
    images: [
      "/Product/cabinet/20.png",
      "/Product/cabinet/30.png",
      "/Product/cabinet/40.png",
      "/Product/cabinet/50.png",
      "/Product/cabinet/disc1.png",
      "/Product/cabinet/disc2.png",
      "/Product/cabinet/disc3.png",
    ],
  },
  // Container Type Power Supply products
  {
    id: "container-con1",
    name: "Container Type Power Supply",
    subtitle: "Utility-scale containerized BESS and hybrid power system",
    category: "cabinet",
    tag: "Off-Grid Power Generation System",
    image: "/Product/containertype/con1.png",
    images: [
      "/Product/containertype/con1.png",
      "/Product/containertype/prod1.png",
      "/Product/containertype/prod2.png",
      "/Product/containertype/prod3.png",
      "/Product/containertype/prod4.png",
      "/Product/containertype/prod5.png",
      "/Product/containertype/prod6.png",
    ],
  },
];

// Helper function to get product by ID
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

// Extended product details (can be expanded with more details)
export const productDetails: Record<string, {
  description: string;
  variations: ProductVariation[];
  specifications: { label: string; value: string }[];
  features: string[];
}> = {
  "ev-charging-53": {
    description: "DPEV-160KM  - Dual-Gun DC high-power fast charger. Advanced DC fast charging station with dual-gun capability, designed for commercial and public use. Features smart monitoring, payment integration, and remote management capabilities. Ideal for premium charging hubs, expressway service areas, and sites serving EVs that support higher charging power. Faster sessions, future-proof for newer EVs. Supports single-gun full power or dual-gun current sharing modes.",
    variations: [
      { name: "Model", value: "DPEV-160KM ", description: "160kW / 240kW Dual-Gun DC Charger" },
      { name: "Type", value: "High-power fast charger" },
      { name: "Rated Power", value: "160kW (DPEV-160KM) " },
      { name: "Connector Type", value: "GBT Standard" },
      { name: "Gun Type", value: "Dual-gun DC Charging Pile" },
      { name: "Output Mode", value: "Single-gun full power, dual-gun current sharing" },
      { name: "Use Cases", value: "Premium charging hubs, Expressway service areas, Sites serving EVs that support higher charging power" },
    ],
    specifications: [
      { label: "Product Name", value: "DPEV-160KM " },
      { label: "Equipment Dimensions", value: "1650×750×575mm" },
      { label: "Gun Line Standard", value: "GBT" },
      { label: "Gun Line Length", value: "5m, 7m" },
      { label: "Input Voltage", value: "380Vac ±15% (A, B, C, N, PE)" },
      { label: "Input Current", value: "< 320A (DPEV-160KM) / < 480A (DPEV-240KM)" },
      { label: "Input Frequency", value: "45 ~ 55Hz" },
      { label: "Output Voltage", value: "150V ~ 1000V" },
      { label: "Maximum Output Current", value: "Single shot 250A" },
      { label: "Rated Power", value: "160kW (DPEV-160KM) " },
      { label: "Display Mode", value: "7-inch Touch LCD Screen (Optional)" },
      { label: "Charging Method", value: "Password, QR Code Scanning, Card Swiping (Optional), VIN (Optional)" },
      { label: "Installation Method", value: "Integrated" },
      { label: "Networking Method", value: "4G, Ethernet (choose one)" },
      { label: "Maximum Efficiency", value: "≥95%" },
      { label: "Power Factor", value: "≥99%" },
      { label: "Voltage Regulation Precision", value: "≤±0.5%" },
      { label: "Current Regulation Precision", value: "≤±1%" },
      { label: "Ripple Coefficient", value: "≤1% (peak value)" },
      { label: "Output Mode", value: "Single-gun full power, dual-gun current sharing" },
      { label: "Operating Temperature", value: "-25 ~ +50°C" },
      { label: "Storage Temperature", value: "-40 ~ +70°C" },
      { label: "Relative Humidity", value: "≤95%" },
      { label: "Protection Functions", value: "Over-voltage protection, under-voltage protection, over-current protection, short-circuit protection, leakage protection, emergency stop protection, grounding continuity protection, relay over-temperature protection, etc." },
      { label: "Atmospheric Pressure", value: "70 ~ 106kPa" },
      { label: "Altitude", value: "≤2000m" },
      { label: "Cooling Method", value: "Forced air cooling" },
      { label: "Protection Level", value: "IP55" },
      { label: "Acoustic Noise", value: "≤ 65dB" },
    ],
    features: [
      "High cost-effectiveness: Highly integrated design, reducing the floor area, and saving on site rental and infrastructure costs",
      "High cost-effectiveness: Core components are designed in a modular manner, allowing for independent disassembly and replacement, significantly reducing the cost of manual maintenance",
      "High-speed fast charging: Supports simultaneous charging of four chargers, and can flexibly allocate power according to the number of vehicles connected and charging requirements",
      "High-speed fast charging: Conversion efficiency exceeds 95%, effectively reducing energy loss during the charging process",
      "Dual-gun simultaneous charging with current sharing capability",
      "High-power fast charging (160kW / 240kW rated power)",
      "Single-gun full power or dual-gun current sharing modes",
      "Future-proof for newer EVs supporting higher charging power",
      "Faster charging sessions with up to 250A output current",
      "7-inch touch LCD screen for user interface",
      "Multiple charging methods: Password, QR Code, Card Swiping, VIN",
      "4G or Ethernet networking options",
      "High efficiency (≥95%) and power factor (≥99%)",
      "Precise voltage and current regulation",
      "Comprehensive protection functions for safe operation",
      "Forced air cooling system",
      "IP55 protection level for outdoor use",
      "Low acoustic noise (≤65dB)",
      "Remote monitoring and diagnostics",
      "Ideal for premium charging hubs and expressway service areas",
    ],
  },
  "ev-charging-59": {
    description:
      "Home smart AC charging station - The household intelligent AC charging station is a core device designed in response to the popularization of new energy vehicles, to meet the daily charging needs of individual users. It can provide a safe, convenient and economical charging experience at home. Through intelligent technology, it realizes the intelligent connection among people, vehicles and charging stations, making charging an integral part of daily life. DPEV-7K – 7 kW Single-Gun AC \"slow\" charger designed as a reliable, everyday AC charging solution. Ideal for locations where vehicles remain parked for longer periods, such as residential, office and hotel parking. Offers dependable performance with low installation cost, making it an excellent choice as a basic amenity charger.",
    variations: [
      { name: "Model", value: "DPEV-7A / DPEV-11A / DPEV-14A / DPEV-21A" },
      { name: "Power Output", value: "7kW / 11kW / 14kW / 21kW" },
      { name: "Connector Type", value: "Type 2 (IEC 62196) - GBT Standard" },
      { name: "Gun Type", value: "Single-gun AC Charging Pile" },
      { name: "Gun Line Length", value: "5m (standard configuration)" },
      { name: "Type", value: "AC \"slow\" charger" },
      {
        name: "Use Cases",
        value:
          "Apartment parking spaces, Enterprise parking spaces, Private parking spaces; Residential, office, hotel parking; locations where cars stay parked for many hours",
      },
      {
        name: "Selling Point",
        value:
          "Low installation cost, suitable as a \"basic amenity\" charger for long-stay parking. Multiple protections, easy to use, intelligent and convenient with 4G connectivity",
      },
    ],
    specifications: [
      { label: "Equipment Dimensions", value: "368×254×100mm (excluding stand column)" },
      { label: "Gun Line Standard", value: "GBT" },
      { label: "Gun Line Length", value: "5m (standard)" },
      { label: "Rated Power", value: "7kW (DPEV-7A)" },
      { label: "Input Voltage", value: "220V±20% (7A/14A) " },
      { label: "Input Current", value: "Single-phase 32A (7A) / Three-phase 16A (11A) / Single-phase 32A×2 (14A) / Three-phase 32A (21A)" },
      { label: "Input Frequency", value: "45~55Hz" },
      { label: "Output Voltage", value: "220V±20% (7A/14A)" },
      { label: "Output Current", value: "32A (7A) / 16A (11A) / 32A×2 (14A) / 32A (21A)" },
      { label: "Display Mode", value: "4.3-inch touch screen" },
      { label: "Charging Mode", value: "RFID card swiping, password charging, mobile phone scanning code (optional)" },
      { label: "Installation Mode", value: "Wall-mounted, floor-standing" },
      { label: "Networking Mode", value: "4G" },
      { label: "Maximum Efficiency", value: "≥95%" },
      { label: "Power Factor", value: "≥99%" },
      { label: "Operating Temperature", value: "-25~+50°C" },
      { label: "Storage Temperature", value: "-40~+70°C" },
      { label: "Relative Humidity", value: "≤95%" },
      { label: "Atmospheric Pressure", value: "70~106kPa" },
      { label: "Altitude", value: "≤2000m" },
      { label: "Protection Level", value: "IP55 (dustproof and waterproof)" },
    ],
    features: [
      "Multiple protections: Electrical protections (overvoltage, undervoltage, overtemperature, short circuit), complying with national and industry safety standards",
      "Wall-mounted installation, compact structure, saves space",
      "4G network connection with various start-up methods (card swiping, code scanning)",
      "Makes full use of off-peak electricity at night to reduce vehicle operating costs",
      "Comprehensive safety protection for personnel, vehicles, and power grid",
      "High-strength flame-retardant material casing with IP55 protection level",
      "National standard AC charging interface, compatible with mainstream new energy vehicle brands",
      "Color touch screen display with user-friendly indicator lights",
      "Remote control and intelligent management",
      "Suitable for apartment, enterprise, and private parking spaces",
      "Intelligent technology enabling connection among people, vehicles and charging stations",
      "Low installation cost, ideal as a basic amenity charger for long-stay parking",
    ],
  },
  "ev-charging-64": {
    description:
      "DPEV-400K - Ultra-high power Dual-Gun DC fast charging solution designed for commercial sites, fleet depots, and urban charging stations. This new generation intelligent charging system provides powerful DC rapid charging capabilities specifically developed for heavy-duty electric vehicles. Features highly integrated design, intelligent power allocation, flexible networking, and comprehensive remote management. Delivers reliable dual-gun simultaneous charging with advanced technologies and high-quality materials ensuring stability and reliability under high-load and long-term operation.",
    variations: [
      {
        name: "Model",
        value: "DPEV-400K",
        description: "400kW Dual-Gun DC Charger",
      },
      {
        name: "Type",
        value: "Ultra-high power dual-gun DC fast charger",
      },
      {
        name: "Rated Power",
        value: "400kW",
      },
      {
        name: "Connector Type",
        value: "GBT Standard",
      },
      {
        name: "Gun Type",
        value: "Dual-gun DC Charging Pile",
      },
      {
        name: "Output Mode",
        value: "Single-gun full power, dual-gun current sharing",
      },
      {
        name: "Use Cases",
        value:
          "Supercharging demonstration stations, Logistics parks, High-end commercial centers, Bus terminals, Commercial sites, fleet depots, urban charging stations, commercial parking, workplace charging, urban DC fast-charging sites, premium charging hubs, new energy electric heavy-duty vehicle charging",
      },
      {
        name: "Supercharging demonstration station",
        value: "Public supercharging facility",
        description: "Ideal for public supercharging stations with multiple charging units under canopies, serving urban and highway locations",
        image: "/Product/EV/red/106.jpg",
      },
      {
        name: "Logistics park",
        value: "Indoor logistics and warehouse charging",
        description: "Perfect for logistics parks and warehouse facilities with indoor charging infrastructure for fleet vehicles",
        image: "/Product/EV/red/107.jpg",
      },
      {
        name: "High-end commercial center",
        value: "Premium commercial building charging",
        description: "Suitable for high-end commercial centers and office complexes with modern charging infrastructure",
        image: "/Product/EV/red/108.jpg",
      },
      {
        name: "Bus terminal",
        value: "Heavy-duty vehicle depot charging",
        description: "Perfect for bus terminals and heavy-duty vehicle depots requiring high-power charging for fleet operations",
        image: "/Product/EV/red/109.jpg",
      },
    ],
    specifications: [
      { label: "Product Name", value: "DPEV-400K" },
      { label: "Equipment Dimensions", value: "1955×800×590mm" },
      { label: "Gun Line Standard", value: "GBT" },
      { label: "Gun Line Length", value: "5m (standard)" },
      { label: "Input Voltage", value: "380Vac ±15% (A, B, C, N, PE)" },
      { label: "Input Current", value: "< 800A" },
      { label: "Input Frequency", value: "45 ~ 55Hz" },
      { label: "Output Voltage", value: "150V ~ 1000V" },
      { label: "Maximum Output Current", value: "Single-gun 300A, Dual-gun 600A" },
      { label: "Rated Power", value: "400kW" },
      { label: "Display Mode", value: "7-inch touch screen" },
      { label: "Charging Method", value: "RFID card swiping, password charging, mobile QR code scanning (optional), VIN recognition (optional)" },
      { label: "Installation Method", value: "Integrated" },
      { label: "Networking Method", value: "4G, Ethernet (choose one)" },
      { label: "Maximum Efficiency", value: "≥95%" },
      { label: "Power Factor", value: "≥99%" },
      { label: "Voltage Regulation Precision", value: "≤±0.5%" },
      { label: "Current Regulation Precision", value: "≤±1%" },
      { label: "Ripple Coefficient", value: "≤1% (peak value)" },
      { label: "Output Mode", value: "Single-gun full power, dual-gun current sharing" },
      { label: "Operating Temperature", value: "-25 ~ +50°C" },
      { label: "Storage Temperature", value: "-40 ~ +70°C" },
      { label: "Relative Humidity", value: "≤95%" },
      { label: "Protection Functions", value: "Over-voltage protection, under-voltage protection, over-current protection, short-circuit protection, leakage protection, emergency stop protection, grounding continuity protection, relay over-temperature protection, etc." },
      { label: "Atmospheric Pressure", value: "70 ~ 106kPa" },
      { label: "Altitude", value: "≤ 2000m" },
      { label: "Cooling Method", value: "Forced air cooling" },
      { label: "Protection Grade", value: "IP55" },
      { label: "Acoustic Noise", value: "≤65dB" },
    ],
    features: [
      "Ultra-fast Charging: Ultra-fast charging speed significantly reduces waiting time for users, enhancing the charging experience and the attractiveness of charging stations",
      "Ultra-fast Charging: The extremely high power capacity implies higher service efficiency and potential profits, increasing the turnover rate and profitability of charging stations",
      "Stable and efficient: The high-efficiency module reduces power loss and features a highly reliable design, ensuring continuous and uninterrupted charging services",
      "Stable and efficient: Equipped with air-cooling and intelligent temperature control systems, it effectively reduces heat loss during the charging process",
      "Intelligent power distribution: Supports simultaneous charging of multiple guns, with power distributed evenly or dynamically as needed",
      "Intelligent power distribution: Utilizes high-efficiency charging modules, with peak efficiency reaching over 95%, reducing operational energy consumption",
      "Investment Protection: Take into account the charging needs of future and higher voltage platform vehicles, avoiding the obsolescence of equipment due to technological updates",
      "Investment Protection: Adapt to the development trend of electric vehicle technology, effectively protecting the long-term interests of investors",
    ],
  },
  "solar-street-f2l": {
    description: "Integrated solar street light featuring all-in-one design with high-efficiency monocrystalline solar panel, intelligent LED lighting, and advanced battery management system. Available in four models (F2-050, F2-080, F2-100, F2-120) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "Integrated Light" },
      {
        name: "F2-050 Model",
        value: "50W LED, 100W Solar Panel",
        description: "LED: 50W | Size: 1319×460×60mm | Battery: 12.8V 45Ah | Solar Panel: 100W | Pole Height: 8m",
        image: "/Product/StreetLamp/f50.png",
      },
      {
        name: "F2-080 Model",
        value: "80W LED, 160W Solar Panel",
        description: "LED: 80W | Size: 1490×640×60mm | Battery: 25.6V 45Ah | Solar Panel: 160W | Pole Height: 9m",
        image: "/Product/StreetLamp/f80.png",
      },
      {
        name: "F2-100 Model",
        value: "100W LED, 200W Solar Panel",
        description: "LED: 100W | Size: 1490×730×60mm | Battery: 25.6V 52Ah | Solar Panel: 200W | Pole Height: 10m",
        image: "/Product/StreetLamp/f100.png",
      },
      {
        name: "F2-120 Model",
        value: "120W LED, 240W Solar Panel",
        description: "LED: 120W | Size: 1650×830×60mm | Battery: 25.6V 60Ah | Solar Panel: 240W | Pole Height: 12m",
        image: "/Product/StreetLamp/f120.png",
      },
      { name: "LED Power", value: "50W (F2-050) / 80W (F2-080) / 100W (F2-100) / 120W (F2-120)" },
      { name: "Solar Panel", value: "100W (F2-050) / 160W (F2-080) / 200W (F2-100) / 240W (F2-120)" },
      { name: "Battery Capacity", value: "12.8V 45Ah (F2-050) / 25.6V 45Ah (F2-080) / 25.6V 52Ah (F2-100) / 25.6V 60Ah (F2-120)" },
      { name: "Pole Height", value: "8m (F2-050) / 9m (F2-080) / 10m (F2-100) / 12m (F2-120)" },
    ],
    specifications: [
      { label: "Item No.", value: "F2-050 / F2-080 / F2-100 / F2-120" },
      { label: "LED Power", value: "50W / 80W / 100W / 120W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "100W / 160W / 200W / 240W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "12.8V 45Ah (F2-050) / 25.6V 45Ah (F2-080) / 25.6V 52Ah (F2-100) / 25.6V 60Ah (F2-120)" },
      { label: "Equipment Size", value: "1319×460×60mm (F2-050) / 1490×640×60mm (F2-080) / 1490×730×60mm (F2-100) / 1650×830×60mm (F2-120)" },
      { label: "Pole Height", value: "8m / 9m / 10m / 12m" },
      { label: "Working Time", value: "All night lighting, 365 days per year (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP67 (Super waterproof design)" },
      { label: "Battery Material", value: "LFP high-temperature resistant material" },
      { label: "Optical Lens", value: "Polycarbonate (PC) outdoor optical lenses" },
      { label: "Safety Protection", value: "Two hardware protections + one software protection" },
    ],
    features: [
      "Precision grade high-quality aluminum alloy die-casting, patented private molds",
      "Integrated design, modular production, and one click installation",
      "Easy installation, no need for wiring, and no worries about power outages and restrictions",
      "LiFePo4 Lithium battery adopted, with reliable quality and long service life",
      "Adopting high-efficiency LED, with a long service life",
      "All night lighting, resistant to high and low temperatures",
      "Using polycarbonate (PC) outdoor optical lenses - High light transmittance, high temperature resistance, aging resistance, no deformation",
      "LFP high-temperature resistant material, with strong safety performance",
      "New material system, ultra long service life",
      "Two hardware protections + one software protection",
      "Protection level IP67, super waterproof design",
      "Integrated PACK process",
      "Anti rainy, with lights on every night for 365 days",
      "Four power variants: 50W, 80W, 100W, 120W LED",
      "High-efficiency monocrystalline solar panels",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
    ],
  },
  "smart-home-smp2": {
    description: "Compact 5.3kWh residential energy storage system designed for home backup power. Perfect for keeping essential loads running during grid outages. Can run 1 HP aircon (~750W) plus lights, fans, TV, laptop, and phone charging simultaneously. With average 1kW draw, provides approximately 4-5 hours of usable runtime. Ideal for backup power during brownouts, sari-sari store lighting with small freezer, off-grid tiny homes, farm huts, and construction site offices. Includes 4×670W solar panels (2.68kW total) for solar charging capability. Perfect for basic rural homes (no AC) or as backup power solution.",
    variations: [
      { name: "Capacity", value: "5.3kWh" },
      { name: "Rated Power", value: "3kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 4 panels (2.68kW total)" },
      { name: "Can Run At Once", value: "1 HP aircon (~750W) plus lights, fans, TV, laptop, phone charging" },
      { name: "Runtime Example", value: "If you draw around 1kW on average → about 4-5 hours usable" },
      { name: "Typical Uses", value: "Backup power for small houses during brownouts; Sari-sari store lights + small freezer for a few hours; Off-grid tiny homes, farm huts, and construction site office; Basic rural home (no AC)" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "3kW / AC 220V" },
      { label: "Battery Capacity", value: "5.3kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 4 panels (2.68kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "3kW" },
      { label: "Typical Runtime", value: "4-5 hours at 1kW average load" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp3": {
    description: "10kWh / 5kW residential energy storage system designed for standard homes and small businesses. Perfect for urban homes that want backup for long brownouts. Can run 1-2 HP aircon, refrigerator, lights, fans, TV, and computers simultaneously. With average 1.5-2kW draw, provides approximately 5-6 hours of usable runtime. Ideal for small clinics, small offices, BPO satellite offices, internet cafés, small resort cottages, and Airbnb units. Includes 6×670W solar panels (4.02kW total) for solar charging capability. Perfect for middle-class homes with 1-2 AC units.",
    variations: [
      { name: "Capacity", value: "10.6kWh" },
      { name: "Rated Power", value: "5kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 6 panels (4.02kW total)" },
      { name: "Can Run At Once", value: "1-2 HP aircon, Refrigerator, Lights, fans, TV, computers" },
      { name: "Runtime Example", value: "If house averages 1.5-2kW → around 5-6 hours usable" },
      { name: "Typical Uses", value: "Urban homes that want backup for long brownouts; Small clinics, small offices, BPO satellite office, internet café; Small resort cottage / Airbnb unit" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "5kW / AC 220V" },
      { label: "Battery Capacity", value: "10.6kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 6 panels (4.02kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "5kW" },
      { label: "Typical Runtime", value: "5-6 hours at 1.5-2kW average load" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp4": {
    description: "15kWh / 5kW residential energy storage system with longer backup duration and same power output as 10kWh model. Same maximum power (5kW) as the 10kWh, but with a larger battery for extended runtime. Perfect for appliances similar to a 10kWh user, but when brownouts last much longer. Ideal for rural homes with frequent long outages, stores with freezers (meat, ice cream) that must stay cold overnight, and small cell sites/telecom repeaters wanting longer autonomy. Includes 8×670W solar panels (5.36kW total) for solar charging capability.",
    variations: [
      { name: "Capacity", value: "15.9kWh" },
      { name: "Rated Power", value: "5kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 8 panels (5.36kW total)" },
      { name: "Can Run At Once", value: "1-2 HP aircon, Refrigerator, Lights, fans, TV, computers (same as 10kWh)" },
      { name: "Runtime Example", value: "Longer backup duration compared to 10kWh model for extended brownouts" },
      { name: "Typical Uses", value: "Rural homes with frequent long outages; Stores with freezers (meat, ice cream) that must stay cold overnight; Small cell sites/telecom repeaters wanting longer autonomy" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for residential and small commercial loads." },
    ],
    specifications: [
      { label: "Rated Power", value: "5kW / AC 220V" },
      { label: "Battery Capacity", value: "15.9kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 8 panels (5.36kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "5kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp5": {
    description: "20kWh / 10kW residential and commercial energy storage system with double advantage: bigger battery + higher power (10kW). Perfect for larger homes and small commercial applications. Can run multiple aircons (3-4 HP total), refrigerator/freezer, lights, computers, pumps, etc., as long as total load is under 10kW. Ideal for large homes with multiple AC units, small resorts or beach houses (several rooms + common area), restaurants, bakeries, and small manufacturing with light machinery, and community facilities like barangay halls, schools, classrooms, and evacuation centers. Includes 12×670W solar panels (8.04kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "21.2kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 12 panels (8.04kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Typical Uses", value: "Large homes with multiple AC units; Small resorts or beach houses (several rooms + common area); Restaurants, bakeries, and small manufacturing with light machinery; Community facilities: barangay halls, schools, classrooms, and evacuation centers" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "21.2kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 12 panels (8.04kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp6": {
    description: "25kWh / 10kW residential and commercial energy storage system with more hours and same power. Same 10kW limit but longer-lasting storage. Perfect when you need a full day-night cycle backup for moderate loads. Ideal for off-grid homes or lodges that must run all night, cold storage rooms for small agri businesses, and small hospitals/clinics needing longer uptime for equipment (but still small scale). Includes 14×670W solar panels (9.38kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "26.5kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 14 panels (9.38kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Runtime Example", value: "Full day-night cycle backup for moderate loads" },
      { name: "Typical Uses", value: "Off-grid homes or lodges that must run all night; Cold storage rooms for small agri businesses; Small hospitals/clinics needing longer uptime for equipment" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "26.5kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 14 panels (9.38kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "smart-home-smp7": {
    description: "30kWh / 10kW mini-microgrid energy storage system. Max 10kW output, but the biggest tank of energy in this list. If the average load is 2-3kW, can often run through the night. Ideal for off-grid communities (several houses sharing one system), remote resorts, island communities, telecom towers + equipment shelters, and farms with pumps, cold storage, and house all in one system. Includes 16×670W solar panels (10.72kW total) for solar charging capability. Considered a mini power plant or microgrid solution.",
    variations: [
      { name: "Capacity", value: "31.8kWh" },
      { name: "Rated Power", value: "10kW / AC 220V" },
      { name: "Type", value: "Mobile Energy Storage Power" },
      { name: "Solar Panel Configuration", value: "36V 670W × 16 panels (10.72kW total)" },
      { name: "Can Run At Once", value: "Multiple aircons (3-4 HP total), Refrigerator/freezer, Lights, computers, pumps, etc., as long as total < 10kW" },
      { name: "Runtime Example", value: "If average load is 2-3kW → can often run through the night" },
      { name: "Typical Uses", value: "Off-grid communities (several houses sharing one system); Remote resorts, island communities; Telecom towers + equipment shelters; Farms with pumps, cold storage, and house all in one system" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "10kW / AC 220V" },
      { label: "Battery Capacity", value: "31.8kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "36V 670W × 16 panels (10.72kW total)" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Max Continuous Load", value: "10kW" },
      { label: "Included Components", value: "Splice bracket + wiring" },
      { label: "Output Voltage", value: "220V AC (380/400V three-phase available)" },
    ],
    features: [
      "A-grade LiFePo4 lithium battery",
      "UPS automatic switching. Computer does not flash for 0.02 seconds",
      "Flexible battery power expansion increase power according to demand",
      "Customized",
      "Stacked Design Easy to install",
      "Support off grid operation Emergency power supply Seamless switching",
      "BMS management system Multiple battery protection",
      "Constant voltage technology, Protecting electrical appliances",
      "Integrated design of inverter and battery",
    ],
  },
  "cabinet-14": {
    description: "Village / industrial-scale cabinet-type energy storage system (215-261 kWh / 100-110 kW). Serious microgrids that can supply tens of houses plus businesses, or one small industrial plant (rice mill complex, ice plant, food processing, shipyard section). Ideal for whole small islands / sitios (dozens of households), LGU projects (solarizing barangays, ports, fish landing centers), and large commercial farms, cold-storage hubs, ice plants. Big models (215-261 kWh, 100-110 kW) suitable for whole small community or industrial site. Includes 144×670W solar panels (96.48kW total) for solar charging capability.",
    variations: [
      { 
        name: "215kWh / 100kW", 
        value: "Village / Industrial-Scale Microgrid",
        description: "215.04kWh battery, 100kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Can supply tens of houses plus businesses, or one small industrial plant.",
        image: "/Product/cabinet/cb14/215.png"
      },
      { 
        name: "233kWh / 110kW", 
        value: "Advanced Village / Industrial-Scale Microgrid",
        description: "232.9kWh battery, 110kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Enhanced capacity for whole small communities or industrial sites.",
        image: "/Product/cabinet/cb14/233.png"
      },
      { 
        name: "261kWh / 110kW", 
        value: "Maximum Capacity Village / Industrial-Scale Microgrid",
        description: "261.2kWh battery, 110kW rated power, 400V/220V output. Includes 144×670W solar panels (96.48kW total). Maximum capacity for the most demanding village or industrial applications.",
        image: "/Product/cabinet/cb14/261.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Can Power", value: "Tens of houses plus businesses, or one small industrial plant (rice mill complex, ice plant, food processing, shipyard section)" },
      { name: "Typical Uses", value: "Whole small islands / sitios (dozens of households); LGU projects (solarizing barangays, ports, fish landing centers); Large commercial farms, cold-storage hubs, ice plants" },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Big models (215-261 kWh, 100-110 kW) → whole small community or industrial site." },
    ],
    specifications: [
      { label: "Rated Power", value: "100kW / 110kW (AC)" },
      { label: "Battery Capacity", value: "215.04kWh / 232.9kWh / 261.2kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 144 panels (96.48kW total)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Serious microgrid capability for village/industrial scale",
      "Can supply tens of houses plus businesses",
      "Perfect for whole small islands / sitios (dozens of households)",
      "Ideal for LGU projects (solarizing barangays, ports, fish landing centers)",
      "Suitable for large commercial farms, cold-storage hubs, ice plants",
      "Can power one small industrial plant (rice mill, ice plant, food processing, shipyard)",
      "Includes 144×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Village / industrial-scale microgrid solution",
    ],
  },
  "cabinet-15": {
    description: "Large-scale industrial / community microgrid cabinet-type energy storage system (466-522 kWh / 220 kW). Ultra-high capacity and power output for large-scale operations. Can power large industrial complexes, multiple commercial facilities, or entire communities. Ideal for utility-scale applications, large manufacturing facilities, and major infrastructure projects requiring massive energy storage capacity.",
    variations: [
      { 
        name: "466kWh / 220kW", 
        value: "Large-Scale Industrial / Community Microgrid",
        description: "465.8kWh battery, 220kW rated power, 400V/220V output. Includes 288×670W solar panels (192.96kW total). Ultra-high capacity for large-scale industrial and community applications.",
        image: "/Product/cabinet/cb15/466.png"
      },
      { 
        name: "522kWh / 220kW", 
        value: "Maximum Capacity Industrial / Community Microgrid",
        description: "522.4kWh battery, 220kW rated power, 400V/220V output. Includes 288×670W solar panels (192.96kW total). Maximum capacity for the most demanding large-scale applications.",
        image: "/Product/cabinet/cb15/522.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "220kW (AC)" },
      { label: "Battery Capacity", value: "465.8kWh / 522.4kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 288 panels (192.96kW)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Ultra-high capacity for large-scale operations",
      "Perfect for large industrial complexes and multiple commercial facilities",
      "Ideal for utility-scale applications and major infrastructure projects",
      "Suitable for entire communities requiring massive energy storage",
      "Includes 288-444×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Large-scale industrial / community microgrid solution",
    ],
  },
  "cabinet-16": {
    description: "Village or island grid cabinet-type energy storage system (783 kWh / 300 kW). Can act as the main power plant for a whole small island barangay with a few hundred households, a school, a clinic, and small businesses; a large resort complex with multiple buildings, pools, restaurants, and laundry; or a cluster of factories (e.g., agro-processing complex). At 150kW average load, provides around 5 hours of storage; with solar, this can cover day + part of night. Includes 444×670W solar panels (297.48kW total) for solar charging capability.",
    variations: [
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Can Act As", value: "Main power plant for: whole small island barangay with a few hundred households, a school, a clinic, and small businesses; large resort complex with multiple buildings, pools, restaurants, and laundry; cluster of factories (e.g., agro-processing complex)" },
      { name: "Battery Runtime", value: "At 150kW average → around 5 hours of storage; with solar, this can cover day + part of night" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Notes", value: "Considered serious microgrid or mini power plant. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 400V/380V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "300kW (AC)" },
      { label: "Battery Capacity", value: "783.6kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 444 panels (297.48kW total)" },
      { label: "Voltage", value: "400V / 220V" },
      { label: "Battery Type", value: "LiFePO4" },
      { label: "Cycle Life", value: "6000+ cycles" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
      { label: "Included Components", value: "Splice bracket + wiring" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Can act as main power plant for whole small island barangays",
      "Perfect for large resort complexes with multiple buildings",
      "Ideal for clusters of factories and agro-processing complexes",
      "At 150kW average load, provides around 5 hours of storage",
      "With solar, can cover day + part of night",
      "Includes 444×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Village or island grid solution",
    ],
  },
  "cabinet-item4": {
    description: "Cabinet-type energy storage system for commercial and industrial facility applications. Available in multiple capacity options from 40kWh to 100kWh. Can power 5-10 small houses, or a water refilling station, rice mill, small cold room, plus office & lighting, or a cell tower + equipment shelter with extra capacity. Ideal for off-grid tourist sites with a few cottages, poultry/piggery/fish farms (lighting, blowers, small machinery), and telecom sites that want to reduce diesel use.",
    variations: [
      { 
        name: "40kWh / 20kW", 
        value: "Small Commercial / Remote Facility",
        description: "40.96kWh battery, 20kW rated power, 380V/220V output. Includes 30×670W solar panels (20.1kW total). Can power: 5-10 small houses, or a water refilling station, rice mill, small cold room, plus office & lighting, or a cell tower + equipment shelter with extra capacity. Market: Off-grid tourist sites with a few cottages, poultry/piggery/fish farms (lighting, blowers, small machinery), telecom sites that want to reduce diesel use.",
        image: "/Product/cabinet/20.png"
      },
      { 
        name: "60kWh / 30kW", 
        value: "Small Community or Larger Business",
        description: "61.4kWh battery, 30kW rated power, 380V/220V output. Includes 40×670W solar panels (26.8kW total). Can power: a small resort (10+ rooms, kitchen, bar, pool pump), a medium agricultural facility (irrigation pumps, storage, office), or a cluster of 10-20 households with controlled use. Market: Island barangays, remote mountain communities, bigger manufacturing workshops (welding, small machines).",
        image: "/Product/cabinet/30.png"
      },
      { 
        name: "80kWh / 40kW", 
        value: "Microgrid for a Barangay Center or Campus",
        description: "83.2kWh battery, 40kW rated power, 380V/220V output. Includes 60×670W solar panels (40.2kW total). Suitable for: school campus (several buildings, lights, fans, computers), barangay center + streetlights + market area, or medium resort or eco-park with many cottages plus common facilities. Good where diesel gensets are currently used daily, and fuel is expensive. Many loads are running at the same time (kitchen, laundry, ACs, pumps).",
        image: "/Product/cabinet/40.png"
      },
      { 
        name: "100kWh / 50kW", 
        value: "Microgrid for a Barangay Center or Campus",
        description: "100.3kWh battery, 50kW rated power, 380V/220V output. Includes 72×670W solar panels (48.24kW total). Suitable for: school campus (several buildings, lights, fans, computers), barangay center + streetlights + market area, or medium resort or eco-park with many cottages plus common facilities. Good where diesel gensets are currently used daily, and fuel is expensive. Many loads are running at the same time (kitchen, laundry, ACs, pumps).",
        image: "/Product/cabinet/50.png"
      },
      { name: "Type", value: "Off-Grid Power Generation System" },
      { name: "Included Components", value: "Splice bracket + wiring" },
      { name: "Simple Explanation", value: "kWh (battery): how long it can run when the sun is gone. kW (rated power): how many appliances/machines can run at the same time. Panels (number of 670W pcs): how fast you can recharge the batteries each day." },
      { name: "Model Size", value: "Smaller models (40-60 kWh, 20-30 kW) → single business or small compound. Mid models (80-100 kWh, 40-50 kW) → school, resort, or barangay center." },
      { name: "Notes", value: "Considered mini power plant or microgrid. Much higher power (kW) can feed many buildings/machines. Higher battery capacity (kWh) can run a site for many hours. Output at 380/400V three-phase + 220V suitable for commercial/industrial loads, pumps, motors, etc. Can power a barangay or a small business commercial." },
    ],
    specifications: [
      { label: "Rated Power", value: "20kW / 30kW / 40kW / 50kW (AC)" },
      { label: "Battery Capacity", value: "40.96kWh / 61.4kWh / 83.2kWh / 100.3kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 30-72 panels (20.1kW - 48.24kW total)" },
      { label: "Voltage", value: "380V / 220V" },
      { label: "Output Voltage", value: "380V/400V three-phase + 220V" },
    ],
    features: [
      "Safe and stable: Equipped with a three-level fire protection system, achieving comprehensive protection of the system, precision liquid cooling temperature control design, and achieving long-term stability",
      "Multiple benefits: Support demand response, virtual power plants, achieve multiple benefits, and support dynamic switching of energy regulation strategies",
      "Flexible and efficient: AC/DC can be independently designed for flexible configuration, with small individual weight and convenient installation",
      "Intelligent collaboration: Intelligent switching strategies for different scenarios: peak shaving and valley filling, capacity management, dynamic capacity expansion, new energy consumption, plan curve response, local and cloud monitoring linkage",
      "Modular cabinet design",
      "Scalable capacity",
      "Remote monitoring",
      "Grid-tie and off-grid compatible",
      "Industrial-grade components",
      "Easy maintenance",
      "Can power 5-10 small houses or commercial facilities",
      "Perfect for off-grid tourist sites and remote facilities",
      "Ideal for agricultural and farming applications",
      "Suitable for telecom sites reducing diesel dependency",
      "Includes 30-72×670W solar panels for solar charging",
      "Complete package with splice bracket and wiring",
      "Mini power plant/microgrid capability",
    ],
  },
  "ev-charging-89": {
    description: "DPEV-60K / DPEV-120K - Dual-Gun DC high-power fast charger. Advanced DC fast charging station with dual-gun capability, designed for commercial and public use. Features smart monitoring, payment integration, and remote management capabilities. Ideal for premium charging hubs, expressway service areas, and sites serving EVs that support higher charging power. Faster sessions, future-proof for newer EVs. Supports single-gun full power or dual-gun current sharing modes.",
    variations: [
      {
        name: "DPEV-60K",
        value: "60kW Dual-Gun DC Charger",
        description: "60kW Dual-Gun DC fast charging station",
      },
      {
        name: "DPEV-120K",
        value: "120kW Dual-Gun DC Charger",
        description: "120kW Dual-Gun DC fast charging station",
      },
      { name: "Type", value: "High-power fast charger" },
      { name: "Rated Power", value: "60kW (DPEV-60K) / 120kW (DPEV-120K)" },
      { name: "Connector Type", value: "GBT Standard" },
      { name: "Gun Type", value: "Dual-gun DC Charging Pile" },
      { name: "Gun Line Standard", value: "GBT" },
      { name: "Gun Line Length", value: "5m (standard)" },
      { name: "Output Mode", value: "Single-gun full power, dual-gun current sharing" },
      {
        name: "Use Cases",
        value:
          "Premium charging hubs, Expressway service areas, Sites serving EVs that support higher charging power",
      },
      {
        name: "Selling Point",
        value:
          "High-power fast charging with dual-gun capability; ideal for commercial and public charging stations; faster sessions, future-proof for newer EVs",
      },
    ],
    specifications: [
      { label: "Product Name", value: "DPEV-60K / DPEV-120K" },
      { label: "Equipment Dimensions", value: "1650×750×575mm" },
      { label: "Gun Line Standard", value: "GBT" },
      { label: "Gun Line Length", value: "5m (standard)" },
      { label: "Input Voltage", value: "380Vac ±15% (A, B, C, N, PE)" },
      { label: "Input Current", value: "< 160A (DPEV-60K) / < 320A (DPEV-120K)" },
      { label: "Input Frequency", value: "45 ~ 55Hz" },
      { label: "Output Voltage", value: "150V ~ 1000V" },
      { label: "Maximum Output Current", value: "Single shot 150A (DPEV-60K) / 250A (DPEV-120K)" },
      { label: "Rated Power", value: "60kW (DPEV-60K) / 120kW (DPEV-120K)" },
      { label: "Display Mode", value: "7-inch touch screen" },
      { label: "Charging Method", value: "RFID card swiping, password charging, mobile QR code scanning (optional), VIN recognition (optional)" },
      { label: "Installation Method", value: "Integrated" },
      { label: "Networking Method", value: "4G, Ethernet (choose one)" },
      { label: "Maximum Efficiency", value: "≥95%" },
      { label: "Power Factor", value: "≥99%" },
      { label: "Voltage Regulation Precision", value: "≤±0.5%" },
      { label: "Current Regulation Precision", value: "≤±1%" },
      { label: "Ripple Coefficient", value: "≤1% (peak value)" },
      { label: "Output Mode", value: "Single-gun full power, dual-gun current sharing" },
      { label: "Operating Temperature", value: "-25 ~ +50°C" },
      { label: "Storage Temperature", value: "-40 ~ +70°C" },
      { label: "Relative Humidity", value: "≤95%" },
      { label: "Protection Functions", value: "Over-voltage protection, under-voltage protection, over-current protection, short-circuit protection, leakage protection, emergency stop protection, grounding continuity protection, relay over-temperature protection, etc." },
      { label: "Atmospheric Pressure", value: "70 ~ 106kPa" },
      { label: "Altitude", value: "≤ 2000m" },
      { label: "Cooling Method", value: "Forced air cooling" },
      { label: "Protection Grade", value: "IP55" },
      { label: "Acoustic Noise", value: "≤65dB" },
    ],
    features: [
      "Convenient and easy to use: Low power configuration, effectively reducing energy consumption costs, with low maintenance expenses and high cost-effectiveness",
      "Convenient and easy to use: Compatible with mainstream new energy vehicles on the market, enabling fast and stable charging",
      "Dynamic Allocation: Intelligent power distribution, based on the battery status of the vehicle when dual chargers are connected, automatically optimizes power output to achieve efficient charging",
      "Dynamic Allocation: Multi-level power output, capable of replenishing a significant amount of range for electric vehicles in a short period of time",
      "Secure Protection: Protection level IP55 (dust and water resistance), suitable for various harsh outdoor environments",
      "Secure Protection: Equipped with multiple safety protection functions such as overvoltage protection, undervoltage protection, short circuit protection, and leakage protection",
      "Easy to operate: Rich communication interfaces, connecting to the operation management platform via Ethernet or 4G wireless network",
      "Easy to operate: Large-sized touch display screen, with intuitive and convenient operation, and real-time display of charging information",
      "Dual-gun simultaneous charging with current sharing capability",
      "High-power fast charging (60kW / 120kW rated power)",
      "Single-gun full power or dual-gun current sharing modes",
      "High efficiency (≥95%) and power factor (≥99%)",
      "Precise voltage and current regulation",
      "Forced air cooling system",
      "Low acoustic noise (≤65dB)",
      "Remote monitoring and diagnostics",
      "Ideal for premium charging hubs and expressway service areas",
    ],
  },
  "solar-street-rklv02": {
    description: "Road King-LV02 compact solar street lighting system featuring split design with separate solar panel and LED fixture. Available in multiple models with varying power outputs, pole heights, and battery capacities to suit different lighting requirements. Includes both Split Street Light and All in Two Light configurations.",
    variations: [
      { name: "Light Type", value: "Split Street Light" },
      {
        name: "LVQ2-050 Model",
        value: "50W LED, 100W Solar Panel",
        description: "LED: 50W | Size: 935×415×210mm | Battery: 14.8V 45Ah | Solar Panel: 100W | Pole Height: 8m",
        image: "/Product/StreetLamp/lvq2/l50.png",
      },
      {
        name: "LVQ2-080 Model",
        value: "80W LED, 200W Solar Panel",
        description: "LED: 80W | Size: 935×415×210mm | Battery: 12.8V 90Ah | Solar Panel: 200W | Pole Height: 9m",
        image: "/Product/StreetLamp/lvq2/l80.png",
      },
      {
        name: "LVQ2-100 Model",
        value: "100W LED, 250W Solar Panel",
        description: "LED: 100W | Size: 935×415×210mm | Battery: 25.6V 48Ah | Solar Panel: 250W | Pole Height: 10m",
        image: "/Product/StreetLamp/lvq2/l100.png",
      },
      {
        name: "LVQ2-120 Model",
        value: "120W LED, 300W Solar Panel",
        description: "LED: 120W | Size: 935×415×210mm | Battery: 25.6V 60Ah | Solar Panel: 300W | Pole Height: 12m",
        image: "/Product/StreetLamp/lvq2/l120.png",
      },
      { name: "LED Power", value: "50W (LVQ2-050) / 80W (LVQ2-080) / 100W (LVQ2-100) / 120W (LVQ2-120)" },
      { name: "Solar Panel", value: "100W (LVQ2-050) / 200W (LVQ2-080) / 250W (LVQ2-100) / 300W (LVQ2-120)" },
      { name: "Battery Capacity", value: "14.8V 45Ah (LVQ2-050) / 12.8V 90Ah (LVQ2-080) / 25.6V 48Ah (LVQ2-100) / 25.6V 60Ah (LVQ2-120)" },
      { name: "Pole Height", value: "8m (LVQ2-050) / 9m (LVQ2-080) / 10m (LVQ2-100) / 12m (LVQ2-120)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVQ2-050 / LVQ2-080 / LVQ2-100 / LVQ2-120" },
      { label: "LED Power", value: "50W / 80W / 100W / 120W (Split)" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "100W / 200W / 250W / 300W (Split)" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "14.8V 45Ah (LVQ2-050) / 12.8V 90Ah (LVQ2-080) / 25.6V 48Ah (LVQ2-100) / 25.6V 60Ah (LVQ2-120)" },
      { label: "Equipment Size", value: "935×415×210mm (LVQ2 series)" },
      { label: "Pole Height", value: "8m / 9m / 10m / 12m (Split)" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "Split Street Light design with separate solar panel and LED fixture",
      "All in Two Light integrated design option",
      "Multiple power variants: 20W, 30W, 80W, 100W, 120W LED",
      "High-efficiency monocrystalline solar panels",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
    ],
  },
  "solar-street-rks": {
    description: "Solar Road King Series LVXC2 premium solar street lighting solution featuring all-in-two design with integrated solar panel and LED fixture. Available in two models (LVXC-320, LVXC-330) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "All in Two Light" },
      {
        name: "LVXC-120 Model",
        value: "20W LED, 70W Solar Panel",
        description: "LED: 20W | Size: 495×205×80mm | Battery: 3.2V 65Ah | Solar Panel: 70W | Pole Height: 5m",
        image: "/Product/StreetLamp/lvxc2/c120.png",
      },
      {
        name: "LVXC-130 Model",
        value: "30W LED, 70W Solar Panel",
        description: "LED: 30W | Size: 550×240×100mm | Battery: 3.2V 80Ah | Solar Panel: 70W | Pole Height: 6m",
        image: "/Product/StreetLamp/lvxc2/c130.png",
      },
      { name: "LED Power", value: "20W (LVXC-120) / 30W (LVXC-130)" },
      { name: "Solar Panel", value: "70W (LVXC-120/130)" },
      { name: "Battery Capacity", value: "3.2V 65Ah (LVXC-120) / 3.2V 80Ah (LVXC-130)" },
      { name: "Pole Height", value: "5m (LVXC-120) / 6m (LVXC-130)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVXC-120 / LVXC-130" },
      { label: "LED Power", value: "20W / 30W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "70W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "3.2V 65Ah (LVXC-120) / 3.2V 80Ah (LVXC-130)" },
      { label: "Equipment Size", value: "495×205×80mm (LVXC-120) / 550×240×100mm (LVXC-130)" },
      { label: "Pole Height", value: "5m / 6m" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "All in Two Light integrated design",
      "Two power variants: 20W and 30W LED",
      "High-efficiency monocrystalline solar panels (70W)",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights (5m/6m)",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
      "Compact sizes: 495×205×80mm (LVXC-120) / 550×240×100mm (LVXC-130)",
    ],
  },
  "solar-street-lvxc": {
    description: "Solar Road King Series LVXC3 high-performance solar street lighting system featuring all-in-two design with integrated solar panel and LED fixture. Available in two models (LVXC-320, LVXC-330) with varying power outputs and pole heights to suit different lighting requirements.",
    variations: [
      { name: "Light Type", value: "All in Two Light" },
      {
        name: "LVXC-320 Model",
        value: "20W LED, 70W Solar Panel",
        description: "LED: 20W | Size: 650×300×130mm | Battery: 3.2V 65Ah | Solar Panel: 70W | Pole Height: 5m",
        image: "/Product/StreetLamp/lvxc3/c320.png",
      },
      {
        name: "LVXC-330 Model",
        value: "30W LED, 70W Solar Panel",
        description: "LED: 30W | Size: 650×300×130mm | Battery: 3.2V 80Ah | Solar Panel: 70W | Pole Height: 6m",
        image: "/Product/StreetLamp/lvxc3/c330.png",
      },
      { name: "LED Power", value: "20W (LVXC-320) / 30W (LVXC-330)" },
      { name: "Solar Panel", value: "70W (LVXC-320/330)" },
      { name: "Battery Capacity", value: "3.2V 65Ah (LVXC-320) / 3.2V 80Ah (LVXC-330)" },
      { name: "Pole Height", value: "5m (LVXC-320) / 6m (LVXC-330)" },
    ],
    specifications: [
      { label: "Item No.", value: "LVXC-320 / LVXC-330" },
      { label: "LED Power", value: "20W / 30W" },
      { label: "LED Efficiency", value: "≥160lm/W" },
      { label: "Solar Panel Power", value: "70W" },
      { label: "Solar Panel Type", value: "Monocrystalline" },
      { label: "Battery Type", value: "Lithium (LiFePO4)" },
      { label: "Battery Voltage & Capacity", value: "3.2V 65Ah (LVXC-320) / 3.2V 80Ah (LVXC-330)" },
      { label: "Equipment Size", value: "650×300×130mm" },
      { label: "Pole Height", value: "5m / 6m" },
      { label: "Working Time", value: "12+ hours (3-5 rainy days backup)" },
      { label: "Protection Level", value: "IP65" },
    ],
    features: [
      "All in Two Light integrated design",
      "Two power variants: 20W and 30W LED",
      "High-efficiency monocrystalline solar panels (70W)",
      "Lithium battery with advanced management system",
      "Intelligent light control (PIR sensor)",
      "Auto dimming function",
      "Weather-resistant construction (IP65)",
      "Easy installation with recommended pole heights (5m/6m)",
      "Maintenance-free operation",
      "Long working time with 3-5 rainy days backup",
      "Compact size: 650×300×130mm",
    ],
  },
  "container-con1": {
    description: "Small utility-level / industrial park containerized Battery Energy Storage System (BESS) and hybrid power system. Designed for significant energy demands equivalent to small utility operations or industrial parks. Available in multiple capacity configurations from 1075kWh to 2700kWh, with rated power options of 500kW or 1000kW AC. Ideal for main power for small island towns (currently using diesel generators), industrial park or export zone tenants (cold-storage hubs, fish ports, mining camps), and large university or hospital campuses or combined municipal loads. When paired with big solar and possibly backup diesel, can provide 24/7 coverage. For average demand of 250-300 kW, provides roughly 3-4 hours of battery at full output. At 150 kW average → around 5 hours of storage; with solar, this can cover day + part of night.",
    variations: [
      {
        name: "1075kWh System",
        value: "500KW/AC, 1075.2kWh Battery, 728×670W Solar Panels",
        description: "Rated Power: 500KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1075.2kWh | Solar Panel: 670W × 728PCS (487.76kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "500kW (AC)" },
          { label: "Battery Capacity", value: "1075.2kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 728 panels (487.76kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "1205kWh System",
        value: "500KW/AC, 1205.76kWh Battery, 728×670W Solar Panels",
        description: "Rated Power: 500KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1205.76kWh | Solar Panel: 670W × 728PCS (487.76kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "500kW (AC)" },
          { label: "Battery Capacity", value: "1205.76kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 728 panels (487.76kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "1800kWh System",
        value: "1000KW/AC, 1806.3kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 1806.3kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "1806.3kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2000kWh System",
        value: "1000KW/AC, 2025.67kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2025.67kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2025.67kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2300kWh System",
        value: "1000KW/AC, 2362.28kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2362.28kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2362.28kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      {
        name: "2700kWh System",
        value: "1000KW/AC, 2700.9kWh Battery, 1484×670W Solar Panels",
        description: "Rated Power: 1000KW/AC | Voltage: 400V/220V | Lithium Battery Capacity: 2700.9kWh | Solar Panel: 670W × 1484PCS (994.28kW total) | Included Components: Splice bracket + wiring",
        specifications: [
          { label: "Rated Power", value: "1000kW (AC)" },
          { label: "Battery Capacity", value: "2700.9kWh (Lithium Battery)" },
          { label: "Solar Panel", value: "670W × 1484 panels (994.28kW total)" },
          { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
            ],
      },
      { name: "Available Capacities", value: "1075kWh / 1205kWh / 1800kWh / 2000kWh / 2300kWh / 2700kWh" },
      { name: "Rated Power", value: "500KW/AC (1075kWh, 1205kWh) / 1000KW/AC (1800kWh, 2000kWh, 2300kWh, 2700kWh)" },
      { name: "Battery Capacity", value: "1075.2kWh - 2700.9kWh (Lithium Battery)" },
      { name: "Solar Panel", value: "670W × 728-1484 panels (487.76kW - 994.28kW total)" },
      { name: "Voltage", value: "400V/220V" },
      { name: "Included Components", value: "Splice bracket + wiring" },
    ],
    specifications: [
      { label: "Rated Power", value: "500kW / 1000kW (AC)" },
      { label: "Battery Capacity", value: "1075.2kWh - 2700.9kWh (Lithium Battery)" },
      { label: "Solar Panel", value: "670W × 728-1484 panels (487kW - 994kW total)" },
      { label: "Output Voltage", value: "400V/380V three-phase + 220V" },
      { label: "Typical Storage", value: "3-6 hours at full output" },
      { label: "Coverage", value: "24/7 with solar + backup diesel" },
    ],
    features: [
      "Small utility-level / industrial park containerized BESS system",
      "Multiple capacity options from 1075kWh to 2700kWh",
      "High power output: 500kW or 1000kW AC",
      "Large-scale solar integration (487kW - 994kW)",
      "Lithium battery technology with advanced BMS",
      "Three-phase + single-phase output (400V/380V + 220V)",
      "24/7 coverage when paired with solar + backup diesel",
      "3-6 hours of battery storage at full output",
      "Complete system with splice bracket and wiring",
      "Ideal for small island towns replacing diesel generators",
      "Suitable for industrial parks, export zones, and mining camps",
      "Perfect for large university or hospital campuses",
      "Containerized design for easy deployment and relocation",
      "Scalable solution for utility-scale energy storage",
    ],
  },
};

